<?php
/**
 * Advanced Location Detection
 *
 * @author    Rolige <www.rolige.com>
 * @copyright 2011-2019 Rolige - All Rights Reserved
 * @license   Proprietary and confidential
 */

@ini_set('max_execution_time', 0);

$sql = array();

$sql[] = 'CREATE TABLE IF NOT EXISTS `'._DB_PREFIX_.'rg_locationdetection_country` (
    `id_country` int(10) NOT NULL AUTO_INCREMENT,
    `country_iso_code` varchar(3) NOT NULL,
    `currency_iso_code` varchar(3) NOT NULL,
    `currency_name` varchar(32) NOT NULL,
    `lang_iso_code_first` varchar(2) DEFAULT NULL,
    `lang_name_first` varchar(32) DEFAULT NULL,
    `lang_iso_code_second` varchar(2) DEFAULT NULL,
    `lang_name_second` varchar(32) DEFAULT NULL,
    `lang_iso_code_third` varchar(2) DEFAULT NULL,
    `lang_name_third` varchar(32) DEFAULT NULL,
    `id_carrier` int(11) unsigned NOT NULL DEFAULT \'0\',
    `active` tinyint(1) unsigned NOT NULL DEFAULT \'1\',
    PRIMARY KEY  (`id_country`)
) ENGINE='._MYSQL_ENGINE_.' DEFAULT CHARSET=utf8;';

$sql[] = 'INSERT INTO `'._DB_PREFIX_."rg_locationdetection_country` (`id_country`, `country_iso_code`, `currency_iso_code`, `currency_name`, `lang_iso_code_first`, `lang_name_first`, `lang_iso_code_second`, `lang_name_second`, `lang_iso_code_third`, `lang_name_third`, `id_carrier`, `active`) VALUES
(1, 'DE', 'EUR', 'Euro', 'DE', 'German', '', '', '', '', 0, 1),
(2, 'AT', 'EUR', 'Euro', 'DE', 'German', '', '', '', '', 0, 1),
(3, 'BE', 'EUR', 'Euro', 'NL', 'Dutch', 'FR', 'French', 'DE', 'German', 0, 1),
(4, 'CA', 'CAD', 'Canadian Dollar', 'EN', 'English (USA)', 'FR', 'French', 'GB', 'English (UK)', 0, 1),
(5, 'CN', 'CNY', 'Chinese Yuan Renminbi', 'ZH', 'Chinese-Simplified', '', '', '', '', 0, 1),
(6, 'ES', 'EUR', 'Euro', 'ES', 'Spanish', '', '', '', '', 0, 1),
(7, 'FI', 'EUR', 'Euro', 'FI', 'Finnish', 'SV', 'Swedish', '', '', 0, 1),
(8, 'FR', 'EUR', 'Euro', 'FR', 'French', '', '', '', '', 0, 1),
(9, 'GR', 'EUR', 'Euro', 'EL', 'Greek', '', '', '', '', 0, 1),
(10, 'IT', 'EUR', 'Euro', 'IT', 'Italian', '', '', '', '', 0, 1),
(11, 'JP', 'JPY', 'Japanese Yen', 'JA', 'Japanese', '', '', '', '', 0, 1),
(12, 'LU', 'EUR', 'Euro', 'FR', 'French', 'DE', 'German', '', '', 0, 1),
(13, 'NL', 'EUR', 'Euro', 'NL', 'Dutch', '', '', '', '', 0, 1),
(14, 'PL', 'PLN', 'Polish Zloty', 'PL', 'Polish', '', '', '', '', 0, 1),
(15, 'PT', 'EUR', 'Euro', 'PT', 'Portuguese', '', '', '', '', 0, 1),
(16, 'CZ', 'CZK', 'Czech Koruna', 'CS', 'Czech', 'SK', 'Slovak', '', '', 0, 1),
(17, 'GB', 'GBP', 'British Pound', 'GB', 'English (UK)', 'EN', 'English (USA)', 'PL', 'Polish', 0, 1),
(18, 'SE', 'SEK', 'Swedish Krona', 'SV', 'Swedish', '', '', '', '', 0, 1),
(19, 'CH', 'CHF', 'Swiss Franc', 'DE', 'German', 'FR', 'French', 'IT', 'Italian', 0, 1),
(20, 'DK', 'DKK', 'Danish Krone', 'DA', 'Danish', '', '', '', '', 0, 1),
(21, 'US', 'USD', 'US Dollar', 'EN', 'English (USA)', '', '', '', '', 0, 1),
(22, 'HK', 'HKD', 'Hong Kong Dollar', 'EN', 'English (USA)', 'ZH', 'Chinese-Simplified', '', '', 0, 1),
(23, 'NO', 'NOK', 'Norwegian Kroner', 'NO', 'Norwegian', 'NN', 'Nynorsk (Norwegian)', '', '', 0, 1),
(24, 'AU', 'AUD', 'Australian Dollar', 'EN', 'English (USA)', '', '', '', '', 0, 1),
(25, 'SG', 'SGD', 'Singapore Dollar', 'EN', 'English (USA)', 'MS', 'Malay', '', '', 0, 1),
(26, 'IE', 'EUR', 'Euro', 'GA', 'Irish', 'EN', 'English (USA)', '', '', 0, 1),
(27, 'NZ', 'NZD', 'New Zealand Dollar', 'EN', 'English (USA)', '', '', '', '', 0, 1),
(28, 'KR', 'KRW', 'South-Korean Won', 'KO', 'Korean', '', '', '', '', 0, 1),
(29, 'IL', 'ILS', 'Israeli New Shekel', 'HE', 'Hebrew', 'AR', 'Arabic', '', '', 0, 1),
(30, 'ZA', 'ZAR', 'South African Rand', 'AF', 'Afrikaans', 'EN', 'English (USA)', '', '', 0, 1),
(31, 'NG', 'NGN', 'Nigerian Naira', 'EN', 'English (USA)', '', '', '', '', 0, 1),
(32, 'CI', 'XOF', 'CFA Franc BCEAO', 'FR', 'French', '', '', '', '', 0, 1),
(33, 'TG', 'XOF', 'CFA Franc BCEAO', 'FR', 'French', '', '', '', '', 0, 1),
(34, 'BO', 'BOB', 'Bolivian Boliviano', 'ES', 'Spanish', '', '', '', '', 0, 1),
(35, 'MU', 'MUR', 'Mauritius Rupee', 'EN', 'English (USA)', '', '', '', '', 0, 1),
(36, 'RO', 'RON', 'Polish Zloty', 'RO', 'Romanian', '', '', '', '', 0, 1),
(37, 'SK', 'EUR', 'Euro', 'SK', 'Slovak', '', '', '', '', 0, 1),
(38, 'DZ', 'DZD', 'Algerian Dinar', 'AR', 'Arabic', '', '', '', '', 0, 1),
(39, 'AS', 'USD', 'US Dollar', 'EN', 'English (USA)', '', '', '', '', 0, 1),
(40, 'AD', 'EUR', 'Euro', 'CA', 'Catalan', '', '', '', '', 0, 1),
(41, 'AO', 'AOA', 'Angolan Kwanza', 'PT', 'Portuguese', '', '', '', '', 0, 1),
(42, 'AI', 'XCD', 'East Caribbean Dollar', 'EN', 'English (USA)', '', '', '', '', 0, 1),
(43, 'AG', 'XCD', 'East Caribbean Dollar', 'EN', 'English (USA)', '', '', '', '', 0, 1),
(44, 'AR', 'ARS', 'Argentine Peso', 'AG', 'Spanish (Argentina)', 'ES', 'Spanish', '', '', 0, 1),
(45, 'AM', 'AMD', 'Armenian Dram', 'HY', 'Armenian', 'RU', 'Russian', '', '', 0, 1),
(46, 'AW', 'AWG', 'Aruban Florin', 'NL', 'Dutch', '', '', '', '', 0, 1),
(47, 'AZ', 'AZN', 'Azerbaijan New Manat', 'AZ', 'Azerbaijani', 'HY', 'Armenian', '', '', 0, 1),
(48, 'BS', 'BSD', 'Bahamian Dollar', 'EN', 'English (USA)', '', '', '', '', 0, 1),
(49, 'BH', 'BHD', 'Bahraini Dinar', 'AR', 'Arabic', '', '', '', '', 0, 1),
(50, 'BD', 'BDT', 'Bangladeshi Taka', 'BN', 'Bengali', '', '', '', '', 0, 1),
(51, 'BB', 'BBD', 'Barbados Dollar', 'EN', 'English (USA)', '', '', '', '', 0, 1),
(52, 'BY', 'BYR', 'Belarusian Ruble', 'RU', 'Russian', '', '', '', '', 0, 1),
(53, 'BZ', 'BZD', 'Belize Dollar', 'EN', 'English (USA)', 'ES', 'Spanish', '', '', 0, 1),
(54, 'BJ', 'XOF', 'CFA Franc BCEAO', 'FR', 'French', '', '', '', '', 0, 1),
(55, 'BM', 'BMD', 'Bermudian Dollar', 'EN', 'English (USA)', '', '', '', '', 0, 1),
(56, 'BT', 'BTN', 'Bhutan Ngultrum', 'EN', 'English (USA)', '', '', '', '', 0, 1),
(57, 'BW', 'BWP', 'Botswana Pula', 'EN', 'English (USA)', '', '', '', '', 0, 1),
(58, 'BR', 'BRL', 'Brazilian Real', 'PT', 'Portuguese', '', '', '', '', 0, 1),
(59, 'BN', 'BND', 'Brunei Dollar', 'MS', 'Malay', '', '', '', '', 0, 1),
(60, 'BF', 'XOF', 'CFA Franc BCEAO', 'FR', 'French', '', '', '', '', 0, 1),
(61, 'MM', 'MMK', 'Myanmar Kyat', 'EN', 'English (USA)', '', '', '', '', 0, 1),
(62, 'BI', 'BIF', 'Burundi Franc', 'FR', 'French', '', '', '', '', 0, 1),
(63, 'KH', 'KHR', 'Cambodian Riel', 'FR', 'French', 'EN', 'English (USA)', '', '', 0, 1),
(64, 'CM', 'XAF', 'CFA Franc BEAC', 'EN', 'English (USA)', 'FR', 'French', '', '', 0, 1),
(65, 'CV', 'CVE', 'Cape Verde Escudo', 'PT', 'Portuguese', '', '', '', '', 0, 1),
(66, 'CF', 'XAF', 'CFA Franc BEAC', 'FR', 'French', '', '', '', '', 0, 1),
(67, 'TD', 'XAF', 'CFA Franc BEAC', 'FR', 'French', 'AR', 'Arabic', '', '', 0, 1),
(68, 'CL', 'CLP', 'Chilean Peso', 'ES', 'Spanish', '', '', '', '', 0, 1),
(69, 'CO', 'COP', 'Colombian Peso', 'CB', 'Spanish (Colombia)', 'ES', 'Spanish', '', '', 0, 1),
(70, 'KM', 'KMF', 'Comoros Franc', 'AR', 'Arabic', 'FR', 'French', '', '', 0, 1),
(71, 'CD', 'CDF', 'Congolese Franc', 'FR', 'French', '', '', '', '', 0, 1),
(72, 'CG', 'XAF', 'CFA Franc BEAC', 'FR', 'French', '', '', '', '', 0, 1),
(73, 'CR', 'CRC', 'Costa Rican Colon', 'ES', 'Spanish', '', '', '', '', 0, 1),
(74, 'HR', 'HRK', 'Croatian Kuna', 'HR', 'Croatian', '', '', '', '', 0, 1),
(75, 'CU', 'CUP', 'Cuban Peso', 'ES', 'Spanish', '', '', '', '', 0, 1),
(76, 'CY', 'EUR', 'Euro', 'EL', 'Greek', 'TR', 'Turkish', 'HY', 'Armenian', 0, 1),
(77, 'DJ', 'DJF', 'Djibouti Franc', 'FR', 'French', 'AR', 'Arabic', '', '', 0, 1),
(78, 'DM', 'XCD', 'East Caribbean Dollar', 'EN', 'English (USA)', '', '', '', '', 0, 1),
(79, 'DO', 'DOP', 'Dominican R. Peso', 'ES', 'Spanish', '', '', '', '', 0, 1),
(80, 'TL', 'USD', 'US Dollar', 'PT', 'Portuguese', '', '', '', '', 0, 1),
(81, 'EC', 'USD', 'US Dollar', 'ES', 'Spanish', '', '', '', '', 0, 1),
(82, 'EG', 'EGP', 'Egyptian Pound', 'AR', 'Arabic', '', '', '', '', 0, 1),
(83, 'SV', 'SVC', 'El Salvador Colon', 'ES', 'Spanish', '', '', '', '', 0, 1),
(84, 'GQ', 'XAF', 'CFA Franc BEAC', 'ES', 'Spanish', 'FR', 'French', '', '', 0, 1),
(85, 'ER', 'ERN', 'Eritrean Nakfa', 'AR', 'Arabic', 'EN', 'English (USA)', '', '', 0, 1),
(86, 'EE', 'EUR', 'Euro', 'ET', 'Estonian', '', '', '', '', 0, 1),
(87, 'ET', 'ETB', 'Ethiopian Birr', 'EN', 'English (USA)', 'AR', 'Arabic', '', '', 0, 1),
(88, 'FK', 'FKP', 'Falkland Islands Pound', 'EN', 'English (USA)', '', '', '', '', 0, 1),
(89, 'FO', 'DKK', 'Danish Krone', 'DA', 'Danish', 'NO', 'Norwegian', 'EN', 'English (USA)', 0, 1),
(90, 'FJ', 'FJD', 'Fiji Dollar', 'EN', 'English (USA)', '', '', '', '', 0, 1),
(91, 'GA', 'XAF', 'CFA Franc BEAC', 'FR', 'French', '', '', '', '', 0, 1),
(92, 'GM', 'GMD', 'Gambian Dalasi', 'EN', 'English (USA)', '', '', '', '', 0, 1),
(93, 'GE', 'GEL', 'Georgian Lari', 'KA', 'Georgian', '', '', '', '', 0, 1),
(94, 'GH', 'GHS', 'Ghanaian New Cedi', 'EN', 'English (USA)', '', '', '', '', 0, 1),
(95, 'GD', 'XCD', 'East Caribbean Dollar', 'EN', 'English (USA)', '', '', '', '', 0, 1),
(96, 'GL', 'DKK', 'Danish Krone', 'DA', 'Danish', '', '', '', '', 0, 1),
(97, 'GI', 'GIP', 'Gibraltar Pound', 'EN', 'English (USA)', '', '', '', '', 0, 1),
(98, 'GP', 'EUR', 'Euro', 'FR', 'French', '', '', '', '', 0, 1),
(99, 'GU', 'USD', 'US Dollar', 'EN', 'English (USA)', 'ES', 'Spanish', '', '', 0, 1),
(100, 'GT', 'GTQ', 'Guatemalan Quetzal', 'ES', 'Spanish', '', '', '', '', 0, 1),
(101, 'GG', 'GGP', 'Guernsey Pound', 'EN', 'English (USA)', 'FR', 'French', '', '', 0, 1),
(102, 'GN', 'GNF', 'Guinea Franc', 'FR', 'French', '', '', '', '', 0, 1),
(103, 'GW', 'XOF', 'CFA Franc BCEAO', 'PT', 'Portuguese', '', '', '', '', 0, 1),
(104, 'GY', 'GYD', 'Guyanese Dollar', 'EN', 'English (USA)', '', '', '', '', 0, 1),
(105, 'HT', 'HTG', 'Haitian Gourde', 'FR', 'French', '', '', '', '', 0, 1),
(106, 'HM', 'AUD', 'Australian Dollar', 'EN', 'English (USA)', '', '', '', '', 0, 1),
(107, 'VA', 'EUR', 'Euro', 'IT', 'Italian', 'FR', 'French', '', '', 0, 1),
(108, 'HN', 'HNL', 'Honduran Lempira', 'ES', 'Spanish', '', '', '', '', 0, 1),
(109, 'IS', 'ISK', 'Iceland Krona', 'EN', 'English (USA)', 'DA', 'Danish', 'DE', 'German ', 0, 1),
(110, 'IN', 'INR', 'Indian Rupee', 'EN', 'English (USA)', '', '', '', '', 0, 1),
(111, 'ID', 'IDR', 'Indonesian Rupiah', 'ID', 'Indonesian', '', '', '', '', 0, 1),
(112, 'IR', 'IRR', 'Iranian Rial', 'FA', 'Persian', '', '', '', '', 0, 1),
(113, 'IQ', 'IQD', 'Iraqi Dinar', 'AR', 'Arabic', '', '', '', '', 0, 1),
(114, 'IM', 'GBP', 'British Pound', 'EN', 'English (USA)', '', '', '', '', 0, 1),
(115, 'JM', 'JMD', 'Jamaican Dollar', 'EN', 'English (USA)', '', '', '', '', 0, 1),
(116, 'JE', 'GBP', 'British Pound', 'EN', 'English (USA)', 'FR', 'French', '', '', 0, 1),
(117, 'JO', 'JOD', 'Jordanian Dinar', 'AR', 'Arabic', '', '', '', '', 0, 1),
(118, 'KZ', 'KZT', 'Kazakhstan Tenge', 'RU', 'Russian', '', '', '', '', 0, 1),
(119, 'KE', 'KES', 'Kenyan Shilling', 'EN', 'English (USA)', '', '', '', '', 0, 1),
(120, 'KI', 'AUD', 'Australian Dollar', 'EN', 'English (USA)', '', '', '', '', 0, 1),
(121, 'KP', 'KPW', 'North Korean Won', 'KO', 'Korean', '', '', '', '', 0, 1),
(122, 'KW', 'KWD', 'Kuwaiti Dinar', 'AR', 'Arabic', '', '', '', '', 0, 1),
(123, 'KG', 'KGS', 'Kyrgyzstanian Som', 'RU', 'Russian', '', '', '', '', 0, 1),
(124, 'LA', 'LAK', 'Lao Kip', 'LO', 'Lao', '', '', '', '', 0, 1),
(125, 'LV', 'EUR', 'Euro', 'LV', 'Latvian', '', '', '', '', 0, 1),
(126, 'LB', 'LBP', 'Lebanese Pound', 'AR', 'Arabic', 'FR', 'French', '', '', 0, 1),
(127, 'LS', 'LSL', 'Lesotho Loti', 'EN', 'English (USA)', '', '', '', '', 0, 1),
(128, 'LR', 'LRD', 'Liberian Dollar', 'EN', 'English (USA)', '', '', '', '', 0, 1),
(129, 'LY', 'LYD', 'Libyan Dinar', 'AR', 'Arabic', '', '', '', '', 0, 1),
(130, 'LI', 'CHF', 'Swiss Franc', 'DE', 'German', '', '', '', '', 0, 1),
(131, 'LT', 'EUR', 'Euro', 'LT', 'Lithuanian', '', '', '', '', 0, 1),
(132, 'MO', 'MOP', 'Macau Pataca', 'ZH', 'Chinese-Simplified', 'PT', 'Portuguese', '', '', 0, 1),
(133, 'MK', 'MKD', 'Macedonian Denar', 'MK', 'Macedonian', '', '', '', '', 0, 1),
(134, 'MG', 'MGA', 'Malagasy Ariary', 'FR', 'French', '', '', '', '', 0, 1),
(135, 'MW', 'MWK', 'Malawi Kwacha', 'EN', 'English (USA)', '', '', '', '', 0, 1),
(136, 'MY', 'MYR', 'Malaysian Ringgit', 'MS', 'Malay', 'EN', 'English (USA)', 'ZH', 'Chinese-Simplified', 0, 1),
(137, 'MV', 'MVR', 'Maldive Rufiyaa', 'EN', 'English (USA)', '', '', '', '', 0, 1),
(138, 'ML', 'XOF', 'CFA Franc BCEAO', 'FR', 'French', '', '', '', '', 0, 1),
(139, 'MT', 'EUR', 'Euro', 'EN', 'English (USA)', '', '', '', '', 0, 1),
(140, 'MH', 'USD', 'US Dollar', 'EN', 'English (USA)', '', '', '', '', 0, 1),
(141, 'MQ', 'EUR', 'Euro', 'FR', 'French', '', '', '', '', 0, 1),
(142, 'MR', 'MRO', 'Mauritanian Ouguiya', 'AR', 'Arabic', '', '', '', '', 0, 1),
(143, 'HU', 'HUF', 'Hungarian Forint', 'HU', 'Hungarian', '', '', '', '', 0, 1),
(144, 'YT', 'EUR', 'Euro', 'FR', 'French', '', '', '', '', 0, 1),
(145, 'MX', 'MXN', 'Mexican Peso', 'MX', 'Spanish (Mexican)', 'ES', 'Spanish', '', '', 0, 1),
(146, 'FM', 'USD', 'US Dollar', 'EN', 'English (USA)', '', '', '', '', 0, 1),
(147, 'MD', 'MDL', 'Moldovan Leu', 'RO', 'Romanian', '', '', '', '', 0, 1),
(148, 'MC', 'EUR', 'Euro', 'FR', 'French', '', '', '', '', 0, 1),
(149, 'MN', 'MNT', 'Mongolian Tugrik', 'RU', 'Russian', '', '', '', '', 0, 1),
(150, 'ME', 'EUR', 'Euro', 'SR', 'Serbian', 'SQ', 'Albanian', '', '', 0, 1),
(151, 'MS', 'XCD', 'East Caribbean Dollar', 'EN', 'English (USA)', '', '', '', '', 0, 1),
(152, 'MA', 'MAD', 'Moroccan Dirham', 'AR', 'Arabic', '', '', '', '', 0, 1),
(153, 'MZ', 'MZN', 'Mozambique New Metical', 'PT', 'Portuguese', '', '', '', '', 0, 1),
(154, 'NA', 'NAD', 'Namibia Dollar', 'EN', 'English (USA)', 'AF', 'Afrikaans', '', '', 0, 1),
(155, 'NR', 'AUD', 'Australian Dollar', 'EN', 'English (USA)', '', '', '', '', 0, 1),
(156, 'NP', 'NPR', 'Nepalese Rupee', 'EN', 'English (USA)', '', '', '', '', 0, 1),
(157, 'AN', 'ANG', 'NL Antillian Guilder', 'NL', 'Dutch', '', '', '', '', 0, 1),
(158, 'NC', 'XPF', 'CFP Franc', 'FR', 'French', '', '', '', '', 0, 1),
(159, 'NI', 'NIO', 'Nicaraguan Cordoba Oro', 'ES', 'Spanish', '', '', '', '', 0, 1),
(160, 'NE', 'XOF', 'CFA Franc BCEAO', 'FR', 'French', '', '', '', '', 0, 1),
(161, 'NU', 'NZD', 'New Zealand Dollar', 'EN', 'English (USA)', '', '', '', '', 0, 1),
(162, 'NF', 'AUD', 'Australian Dollar', 'EN', 'English (USA)', '', '', '', '', 0, 1),
(163, 'MP', 'USD', 'US Dollar', 'EN', 'English (USA)', '', '', '', '', 0, 1),
(164, 'OM', 'OMR', 'Omani Rial', 'AR', 'Arabic', '', '', '', '', 0, 1),
(165, 'PK', 'PKR', 'Pakistan Rupee', 'EN', 'English (USA)', 'UR', 'Urdu', '', '', 0, 1),
(166, 'PW', 'USD', 'US Dollar', 'EN', 'English (USA)', '', '', '', '', 0, 1),
(167, 'PS', 'ILS', 'Israeli New Shekel', 'AR', 'Arabic', '', '', '', '', 0, 1),
(168, 'PA', 'PAB', 'Panamanian Balboa', 'ES', 'Spanish', '', '', '', '', 0, 1),
(169, 'PG', 'PGK', 'Papua New Guinea Kina', 'EN', 'English (USA)', '', '', '', '', 0, 1),
(170, 'PY', 'PYG', 'Paraguay Guarani', 'ES', 'Spanish', '', '', '', '', 0, 1),
(171, 'PE', 'PEN', 'Peruvian Nuevo Sol', 'ES', 'Spanish', '', '', '', '', 0, 1),
(172, 'PH', 'PHP', 'Philippine Peso', 'EN', 'English (USA)', '', '', '', '', 0, 1),
(173, 'PN', 'NZD', 'New Zealand Dollar', 'EN', 'English (USA)', '', '', '', '', 0, 1),
(174, 'PR', 'USD', 'US Dollar', 'ES', 'Spanish', 'EN', 'English (USA)', '', '', 0, 1),
(175, 'QA', 'QAR', 'Qatari Rial', 'AR', 'Arabic', '', '', '', '', 0, 1),
(176, 'RE', 'EUR', 'Euro', 'FR', 'French', '', '', '', '', 0, 1),
(177, 'RU', 'RUB', 'Russian Rouble', 'RU', 'Russian', '', '', '', '', 0, 1),
(178, 'RW', 'RWF', 'Rwandan Franc', 'EN', 'English (USA)', 'FR', 'French', '', '', 0, 1),
(179, 'BL', 'EUR', 'Euro', 'FR', 'French', '', '', '', '', 0, 1),
(180, 'KN', 'XCD', 'East Caribbean Dollar', 'EN', 'English (USA)', '', '', '', '', 0, 1),
(181, 'LC', 'XCD', 'East Caribbean Dollar', 'EN', 'English (USA)', '', '', '', '', 0, 1),
(182, 'MF', 'EUR', 'Euro', 'EN', 'English (USA)', 'FR', 'French', 'NL', 'Dutch', 0, 1),
(183, 'PM', 'EUR', 'Euro', 'FR', 'French', '', '', '', '', 0, 1),
(184, 'VC', 'XCD', 'East Caribbean Dollar', 'EN', 'English (USA)', '', '', '', '', 0, 1),
(185, 'WS', 'WST', 'Samoan Tala', 'EN', 'English (USA)', '', '', '', '', 0, 1),
(186, 'SM', 'EUR', 'Euro', 'IT', 'Italian', '', '', '', '', 0, 1),
(187, 'ST', 'STD', 'Sao Tome/Principe Dobra', 'PT', 'Portuguese', '', '', '', '', 0, 1),
(188, 'SA', 'SAR', 'Saudi Riyal', 'AR', 'Arabic', '', '', '', '', 0, 1),
(189, 'SN', 'XOF', 'CFA Franc BCEAO', 'FR', 'French', '', '', '', '', 0, 1),
(190, 'RS', 'RSD', 'Serbian Dinar', 'SR', 'Serbian', '', '', '', '', 0, 1),
(191, 'SC', 'SCR', 'Seychelles Rupee', 'FR', 'French', 'EN', 'English (USA)', '', '', 0, 1),
(192, 'SL', 'SLL', 'Sierra Leone Leone', 'EN', 'English (USA)', '', '', '', '', 0, 1),
(193, 'SI', 'EUR', 'Euro', 'SI', 'Slovene', 'HR', 'Croatian', 'SR', 'Serbian', 0, 1),
(194, 'SB', 'SBD', 'Solomon Islands Dollar', 'EN', 'English (USA)', '', '', '', '', 0, 1),
(195, 'SO', 'SOS', 'Somali Shilling', 'AR', 'Arabic', '', '', '', '', 0, 1),
(196, 'GS', 'GBP', 'British Pound', 'EN', 'English (USA)', '', '', '', '', 0, 1),
(197, 'LK', 'LKR', 'Sri Lanka Rupee', 'SI', 'Slovene', '', '', '', '', 0, 1),
(198, 'SD', 'SDG', 'Sudanese Pound', 'AR', 'Arabic', 'EN', 'English (USA)', '', '', 0, 1),
(199, 'SR', 'SRD', 'Suriname Dollar', 'NL', 'Dutch', '', '', '', '', 0, 1),
(200, 'SJ', 'NOK', 'Norwegian Kroner', 'NO', 'Norwegian', '', '', '', '', 0, 1),
(201, 'SZ', 'SZL', 'Swaziland Lilangeni', 'EN', 'English (USA)', '', '', '', '', 0, 1),
(202, 'SY', 'SYP', 'Syrian Pound', 'AR', 'Arabic', '', '', '', '', 0, 1),
(203, 'TW', 'TWD', 'Taiwan Dollar', 'ZH', 'Chinese-Simplified', '', '', '', '', 0, 1),
(204, 'TJ', 'TJS', 'Tajikistani Somoni', 'RU', 'Russian', '', '', '', '', 0, 1),
(205, 'TZ', 'TZS', 'Tanzanian Shilling', 'EN', 'English (USA)', '', '', '', '', 0, 1),
(206, 'TH', 'THB', 'Thai Baht', 'TH', 'Thai', '', '', '', '', 0, 1),
(207, 'TK', 'NZD', 'New Zealand Dollar', 'EN', 'English (USA)', '', '', '', '', 0, 1),
(208, 'TO', 'TOP', 'Tonga Pa''anga', 'EN', 'English (USA)', '', '', '', '', 0, 1),
(209, 'TT', 'TTD', 'Trinidad/Tobago Dollar', 'EN', 'English (USA)', '', '', '', '', 0, 1),
(210, 'TN', 'TND', 'Tunisian Dinar', 'AR', 'Arabic', '', '', '', '', 0, 1),
(211, 'TR', 'TRY', 'Turkish Lira', 'TR', 'Turkish', '', '', '', '', 0, 1),
(212, 'TM', 'TMT', 'Turkmenistan New Manat', 'RU', 'Russian', '', '', '', '', 0, 1),
(213, 'TC', 'USD', 'US Dollar', 'EN', 'English (USA)', '', '', '', '', 0, 1),
(214, 'TV', 'AUD', 'Australian Dollar', 'EN', 'English (USA)', '', '', '', '', 0, 1),
(215, 'UG', 'UGX', 'Uganda Shilling', 'EN', 'English (USA)', '', '', '', '', 0, 1),
(216, 'UA', 'UAH', 'Ukraine Hryvnia', 'UK', 'Ukrainian', '', '', '', '', 0, 1),
(217, 'AE', 'AED', 'Utd. Arab Emir. Dirham', 'AR', 'Arabic', '', '', '', '', 0, 1),
(218, 'UY', 'UYU', 'Uruguayan Peso', 'ES', 'Spanish', '', '', '', '', 0, 1),
(219, 'UZ', 'UZS', 'Uzbekistan Som', 'RU', 'Russian', '', '', '', '', 0, 1),
(220, 'VU', 'VUV', 'Vanuatu Vatu', 'EN', 'English (USA)', 'FR', 'French', '', '', 0, 1),
(221, 'VE', 'VEF', 'Venezuelan Bolivar Fuerte', 'ES', 'Spanish', '', '', '', '', 0, 1),
(222, 'VN', 'VND', 'Vietnamese Dong', 'VN', 'Vietnamese', 'EN', 'English (USA)', 'FR', 'French', 0, 1),
(223, 'VG', 'USD', 'US Dollar', 'EN', 'English (USA)', '', '', '', '', 0, 1),
(224, 'VI', 'USD', 'US Dollar', 'EN', 'English (USA)', '', '', '', '', 0, 1),
(225, 'WF', 'XPF', 'CFP Franc', 'FR', 'French', '', '', '', '', 0, 1),
(226, 'EH', 'MAD', 'Moroccan Dirham', 'ES', 'Spanish', '', '', '', '', 0, 1),
(227, 'YE', 'YER', 'Yemeni Rial', 'AR', 'Arabic', '', '', '', '', 0, 1),
(228, 'ZM', 'ZMW', 'Zambian kwacha', 'EN', 'English (USA)', '', '', '', '', 0, 1),
(229, 'ZW', 'USD', 'US Dollar', 'EN', 'English (USA)', '', '', '', '', 0, 1),
(230, 'AL', 'ALL', 'Albanian Lek', 'SQ', 'Albanian', '', '', '', '', 0, 1),
(231, 'AF', 'AFN', 'Afghan Afghani', 'FA', 'Persian', '', '', '', '', 0, 1),
(232, 'AQ', 'USD', 'US Dollar', 'RU', 'Russian', 'EN', 'English (USA)', '', '', 0, 1),
(233, 'BA', 'BAM', 'Bosnian Mark', 'HR', 'Croatian', 'SR', 'Serbian', '', '', 0, 1),
(234, 'BV', 'NOK', 'Norwegian Kroner', 'EN', 'English (USA)', '', '', '', '', 0, 1),
(235, 'IO', 'USD', 'US Dollar', 'EN', 'English (USA)', '', '', '', '', 0, 1),
(236, 'BG', 'BGN', 'Bulgarian Lev', 'BG', 'Bulgarian', '', '', '', '', 0, 1),
(237, 'KY', 'KYD', 'Cayman Islands Dollar', 'EN', 'English (USA)', '', '', '', '', 0, 1),
(238, 'CX', 'AUD', 'Australian Dollar', 'EN', 'English (USA)', '', '', '', '', 0, 1),
(239, 'CC', 'AUD', 'Australian Dollar', 'EN', 'English (USA)', '', '', '', '', 0, 1),
(240, 'CK', 'NZD', 'New Zealand Dollar', 'EN', 'English (USA)', '', '', '', '', 0, 1),
(241, 'GF', 'EUR', 'Euro', 'FR', 'French', '', '', '', '', 0, 1),
(242, 'PF', 'XPF', 'CFP Franc', 'FR', 'French', '', '', '', '', 0, 1),
(243, 'TF', 'EUR', 'Euro', 'FR', 'French', '', '', '', '', 0, 1),
(244, 'AX', 'EUR', 'Euro', 'SV', 'Swedish', '', '', '', '', 0, 1);";

$sql[] = 'CREATE TABLE IF NOT EXISTS `'._DB_PREFIX_.'rg_locationdetection_country_lang` (
    `id_country` int(10) unsigned NOT NULL,
    `id_lang` int(10) unsigned NOT NULL,
    `name` varchar(64) NOT NULL,
    PRIMARY KEY (`id_country`,`id_lang`)
) ENGINE='._MYSQL_ENGINE_.' DEFAULT CHARSET=utf8;';

$country_lang = array(
    array('id_country' => '1', 'en' => 'Germany', 'fr' => 'Allemagne', 'es' => 'Alemania'),
    array('id_country' => '2', 'en' => 'Austria', 'fr' => 'Autriche', 'es' => 'Austria'),
    array('id_country' => '3', 'en' => 'Belgium', 'fr' => 'Belgique', 'es' => 'Bélgica'),
    array('id_country' => '4', 'en' => 'Canada', 'fr' => 'Canada', 'es' => 'Canadá'),
    array('id_country' => '5', 'en' => 'China', 'fr' => 'Chine', 'es' => 'China'),
    array('id_country' => '6', 'en' => 'Spain', 'fr' => 'Espagne', 'es' => 'España'),
    array('id_country' => '7', 'en' => 'Finland', 'fr' => 'Finlande', 'es' => 'Finlandia'),
    array('id_country' => '8', 'en' => 'France', 'fr' => 'France', 'es' => 'Francia'),
    array('id_country' => '9', 'en' => 'Greece', 'fr' => 'Grèce', 'es' => 'Grecia'),
    array('id_country' => '10', 'en' => 'Italy', 'fr' => 'Italie', 'es' => 'Italia'),
    array('id_country' => '11', 'en' => 'Japan', 'fr' => 'Japon', 'es' => 'Japón'),
    array('id_country' => '12', 'en' => 'Luxembourg', 'fr' => 'Luxembourg', 'es' => 'Luxemburgo'),
    array('id_country' => '13', 'en' => 'Netherlands', 'fr' => 'Pays-bas', 'es' => 'Países Bajos'),
    array('id_country' => '14', 'en' => 'Poland', 'fr' => 'Pologne', 'es' => 'Polonia'),
    array('id_country' => '15', 'en' => 'Portugal', 'fr' => 'Portugal', 'es' => 'Portugal'),
    array('id_country' => '16', 'en' => 'Czech Republic', 'fr' => 'République Tchèque', 'es' => 'República Checa'),
    array('id_country' => '17', 'en' => 'United Kingdom', 'fr' => 'Royaume-Uni', 'es' => 'Reino Unido'),
    array('id_country' => '18', 'en' => 'Sweden', 'fr' => 'Suède', 'es' => 'Suecia'),
    array('id_country' => '19', 'en' => 'Switzerland', 'fr' => 'Suisse', 'es' => 'Suiza'),
    array('id_country' => '20', 'en' => 'Denmark', 'fr' => 'Danemark', 'es' => 'Dinamarca'),
    array('id_country' => '21', 'en' => 'United States', 'fr' => 'États-Unis', 'es' => 'EE.UU.'),
    array('id_country' => '22', 'en' => 'HongKong', 'fr' => 'Hong-Kong', 'es' => 'Hong Kong'),
    array('id_country' => '23', 'en' => 'Norway', 'fr' => 'Norvège', 'es' => 'Noruega'),
    array('id_country' => '24', 'en' => 'Australia', 'fr' => 'Australie', 'es' => 'Australia'),
    array('id_country' => '25', 'en' => 'Singapore', 'fr' => 'Singapour', 'es' => 'Singapur'),
    array('id_country' => '26', 'en' => 'Ireland', 'fr' => 'Eire', 'es' => 'Irlanda'),
    array('id_country' => '27', 'en' => 'New Zealand', 'fr' => 'Nouvelle-Zélande', 'es' => 'Nueva Zelanda'),
    array('id_country' => '28', 'en' => 'South Korea', 'fr' => 'Corée du Sud', 'es' => 'Corea del Sur'),
    array('id_country' => '29', 'en' => 'Israel', 'fr' => 'Israël', 'es' => 'Israel'),
    array('id_country' => '30', 'en' => 'South Africa', 'fr' => 'Afrique du Sud', 'es' => 'Sudáfrica'),
    array('id_country' => '31', 'en' => 'Nigeria', 'fr' => 'Nigeria', 'es' => 'Nigeria'),
    array('id_country' => '32', 'en' => 'Ivory Coast', 'fr' => 'Côte d\'Ivoire', 'es' => 'Costa de Marfil'),
    array('id_country' => '33', 'en' => 'Togo', 'fr' => 'Togo', 'es' => 'Togo'),
    array('id_country' => '34', 'en' => 'Bolivia', 'fr' => 'Bolivie', 'es' => 'Bolivia'),
    array('id_country' => '35', 'en' => 'Mauritius', 'fr' => 'Ile Maurice', 'es' => 'Mauricio'),
    array('id_country' => '36', 'en' => 'Romania', 'fr' => 'Roumanie', 'es' => 'Rumania'),
    array('id_country' => '37', 'en' => 'Slovakia', 'fr' => 'Slovaquie', 'es' => 'Eslovaquia'),
    array('id_country' => '38', 'en' => 'Algeria', 'fr' => 'Algérie', 'es' => 'Argelia'),
    array('id_country' => '39', 'en' => 'American Samoa', 'fr' => 'Samoa Américaines', 'es' => 'Samoa Americana'),
    array('id_country' => '40', 'en' => 'Andorra', 'fr' => 'Andorre', 'es' => 'Andorra'),
    array('id_country' => '41', 'en' => 'Angola', 'fr' => 'Angola', 'es' => 'Angola'),
    array('id_country' => '42', 'en' => 'Anguilla', 'fr' => 'Anguilla', 'es' => 'Anguila'),
    array('id_country' => '43', 'en' => 'Antigua and Barbuda', 'fr' => 'Antigua et Barbuda', 'es' => 'Antigua y Barbuda'),
    array('id_country' => '44', 'en' => 'Argentina', 'fr' => 'Argentine', 'es' => 'Argentina'),
    array('id_country' => '45', 'en' => 'Armenia', 'fr' => 'Arménie', 'es' => 'Armenia'),
    array('id_country' => '46', 'en' => 'Aruba', 'fr' => 'Aruba', 'es' => 'Aruba'),
    array('id_country' => '47', 'en' => 'Azerbaijan', 'fr' => 'Azerbaïdjan', 'es' => 'Azerbaiyán'),
    array('id_country' => '48', 'en' => 'Bahamas', 'fr' => 'Bahamas', 'es' => 'Bahamas'),
    array('id_country' => '49', 'en' => 'Bahrain', 'fr' => 'Bahreïn', 'es' => 'Bahrein'),
    array('id_country' => '50', 'en' => 'Bangladesh', 'fr' => 'Bangladesh', 'es' => 'Bangladesh'),
    array('id_country' => '51', 'en' => 'Barbados', 'fr' => 'Barbade', 'es' => 'Barbados'),
    array('id_country' => '52', 'en' => 'Belarus', 'fr' => 'Bélarus', 'es' => 'Belarús'),
    array('id_country' => '53', 'en' => 'Belize', 'fr' => 'Belize', 'es' => 'Belice'),
    array('id_country' => '54', 'en' => 'Benin', 'fr' => 'Bénin', 'es' => 'Benin'),
    array('id_country' => '55', 'en' => 'Bermuda', 'fr' => 'Bermudes', 'es' => 'Bermudas'),
    array('id_country' => '56', 'en' => 'Bhutan', 'fr' => 'Bhoutan', 'es' => 'Bhután'),
    array('id_country' => '57', 'en' => 'Botswana', 'fr' => 'Botswana', 'es' => 'Botswana'),
    array('id_country' => '58', 'en' => 'Brazil', 'fr' => 'Brésil', 'es' => 'Brasil'),
    array('id_country' => '59', 'en' => 'Brunei', 'fr' => 'Brunéi Darussalam', 'es' => 'Brunei'),
    array('id_country' => '60', 'en' => 'Burkina Faso', 'fr' => 'Burkina Faso', 'es' => 'Burkina Faso'),
    array('id_country' => '61', 'en' => 'Burma (Myanmar)', 'fr' => 'Burma (Myanmar)', 'es' => 'Birmania (Myanmar)'),
    array('id_country' => '62', 'en' => 'Burundi', 'fr' => 'Burundi', 'es' => 'Burundi'),
    array('id_country' => '63', 'en' => 'Cambodia', 'fr' => 'Cambodge', 'es' => 'Camboya'),
    array('id_country' => '64', 'en' => 'Cameroon', 'fr' => 'Cameroun', 'es' => 'Camerún'),
    array('id_country' => '65', 'en' => 'Cape Verde', 'fr' => 'Cap-Vert', 'es' => 'Cabo Verde'),
    array('id_country' => '66', 'en' => 'Central African Republic', 'fr' => 'Centrafricaine, République', 'es' => 'República Centroafricana'),
    array('id_country' => '67', 'en' => 'Chad', 'fr' => 'Tchad', 'es' => 'Chad'),
    array('id_country' => '68', 'en' => 'Chile', 'fr' => 'Chili', 'es' => 'Chile'),
    array('id_country' => '69', 'en' => 'Colombia', 'fr' => 'Colombie', 'es' => 'Colombia'),
    array('id_country' => '70', 'en' => 'Comoros', 'fr' => 'Comores', 'es' => 'Comoras'),
    array('id_country' => '71', 'en' => 'Congo, Dem. Republic', 'fr' => 'Congo, Rép. Dém.', 'es' => 'Congo, Rep. Dem.'),
    array('id_country' => '72', 'en' => 'Congo, Republic', 'fr' => 'Congo, Rép.', 'es' => 'Congo, República'),
    array('id_country' => '73', 'en' => 'Costa Rica', 'fr' => 'Costa Rica', 'es' => 'Costa Rica'),
    array('id_country' => '74', 'en' => 'Croatia', 'fr' => 'Croatie', 'es' => 'Croacia'),
    array('id_country' => '75', 'en' => 'Cuba', 'fr' => 'Cuba', 'es' => 'Cuba'),
    array('id_country' => '76', 'en' => 'Cyprus', 'fr' => 'Chypre', 'es' => 'Chipre'),
    array('id_country' => '77', 'en' => 'Djibouti', 'fr' => 'Djibouti', 'es' => 'Djibouti'),
    array('id_country' => '78', 'en' => 'Dominica', 'fr' => 'Dominica', 'es' => 'Dominica'),
    array('id_country' => '79', 'en' => 'Dominican Republic', 'fr' => 'République Dominicaine', 'es' => 'República Dominicana'),
    array('id_country' => '80', 'en' => 'East Timor', 'fr' => 'Timor oriental', 'es' => 'Timor Oriental'),
    array('id_country' => '81', 'en' => 'Ecuador', 'fr' => 'Équateur', 'es' => 'Ecuador'),
    array('id_country' => '82', 'en' => 'Egypt', 'fr' => 'Égypte', 'es' => 'Egipto'),
    array('id_country' => '83', 'en' => 'El Salvador', 'fr' => 'El Salvador', 'es' => 'El Salvador'),
    array('id_country' => '84', 'en' => 'Equatorial Guinea', 'fr' => 'Guinée Équatoriale', 'es' => 'Guinea Ecuatorial'),
    array('id_country' => '85', 'en' => 'Eritrea', 'fr' => 'Érythrée', 'es' => 'Eritrea'),
    array('id_country' => '86', 'en' => 'Estonia', 'fr' => 'Estonie', 'es' => 'Estonia'),
    array('id_country' => '87', 'en' => 'Ethiopia', 'fr' => 'Éthiopie', 'es' => 'Etiopía'),
    array('id_country' => '88', 'en' => 'Falkland Islands', 'fr' => 'Falkland, Îles', 'es' => 'Islas Malvinas'),
    array('id_country' => '89', 'en' => 'Faroe Islands', 'fr' => 'Féroé, Îles', 'es' => 'Islas Feroe'),
    array('id_country' => '90', 'en' => 'Fiji', 'fr' => 'Fidji', 'es' => 'Fiji'),
    array('id_country' => '91', 'en' => 'Gabon', 'fr' => 'Gabon', 'es' => 'Gabón'),
    array('id_country' => '92', 'en' => 'Gambia', 'fr' => 'Gambie', 'es' => 'Gambia'),
    array('id_country' => '93', 'en' => 'Georgia', 'fr' => 'Géorgie', 'es' => 'Georgia'),
    array('id_country' => '94', 'en' => 'Ghana', 'fr' => 'Ghana', 'es' => 'Ghana'),
    array('id_country' => '95', 'en' => 'Grenada', 'fr' => 'Grenade', 'es' => 'Granada'),
    array('id_country' => '96', 'en' => 'Greenland', 'fr' => 'Groenland', 'es' => 'Groenlandia'),
    array('id_country' => '97', 'en' => 'Gibraltar', 'fr' => 'Gibraltar', 'es' => 'Gibraltar'),
    array('id_country' => '98', 'en' => 'Guadeloupe', 'fr' => 'Guadeloupe', 'es' => 'Guadalupe'),
    array('id_country' => '99', 'en' => 'Guam', 'fr' => 'Guam', 'es' => 'Guam'),
    array('id_country' => '100', 'en' => 'Guatemala', 'fr' => 'Guatemala', 'es' => 'Guatemala'),
    array('id_country' => '101', 'en' => 'Guernsey', 'fr' => 'Guernesey', 'es' => 'Guernsey'),
    array('id_country' => '102', 'en' => 'Guinea', 'fr' => 'Guinée', 'es' => 'Guinea'),
    array('id_country' => '103', 'en' => 'Guinea-Bissau', 'fr' => 'Guinée-Bissau', 'es' => 'Guinea-Bissau'),
    array('id_country' => '104', 'en' => 'Guyana', 'fr' => 'Guyana', 'es' => 'Guyana'),
    array('id_country' => '105', 'en' => 'Haiti', 'fr' => 'Haîti', 'es' => 'Haití'),
    array('id_country' => '106', 'en' => 'Heard Island and McDonald Islands', 'fr' => 'Heard, Île et Mcdonald, Îles', 'es' => 'Islas Heard y McDonald Islas'),
    array('id_country' => '107', 'en' => 'Vatican City State', 'fr' => 'Saint-Siege (État de la Cité du Vatican)', 'es' => 'Ciudad del Vaticano'),
    array('id_country' => '108', 'en' => 'Honduras', 'fr' => 'Honduras', 'es' => 'Honduras'),
    array('id_country' => '109', 'en' => 'Iceland', 'fr' => 'Islande', 'es' => 'Islandia'),
    array('id_country' => '110', 'en' => 'India', 'fr' => 'Inde', 'es' => 'India'),
    array('id_country' => '111', 'en' => 'Indonesia', 'fr' => 'Indonésie', 'es' => 'Indonesia'),
    array('id_country' => '112', 'en' => 'Iran', 'fr' => 'Iran', 'es' => 'Irán'),
    array('id_country' => '113', 'en' => 'Iraq', 'fr' => 'Iraq', 'es' => 'Iraq'),
    array('id_country' => '114', 'en' => 'Man Island', 'fr' => 'Man, Île de', 'es' => 'Man, Isla'),
    array('id_country' => '115', 'en' => 'Jamaica', 'fr' => 'Jamaique', 'es' => 'Jamaica'),
    array('id_country' => '116', 'en' => 'Jersey', 'fr' => 'Jersey', 'es' => 'Jersey'),
    array('id_country' => '117', 'en' => 'Jordan', 'fr' => 'Jordanie', 'es' => 'Jordania'),
    array('id_country' => '118', 'en' => 'Kazakhstan', 'fr' => 'Kazakhstan', 'es' => 'Kazajstán'),
    array('id_country' => '119', 'en' => 'Kenya', 'fr' => 'Kenya', 'es' => 'Kenya'),
    array('id_country' => '120', 'en' => 'Kiribati', 'fr' => 'Kiribati', 'es' => 'Kiribati'),
    array('id_country' => '121', 'en' => 'Korea, Dem. Republic of', 'fr' => 'Corée, Rép. Populaire Dém. de', 'es' => 'KOREA, DEM. República de'),
    array('id_country' => '122', 'en' => 'Kuwait', 'fr' => 'Koweït', 'es' => 'Kuwait'),
    array('id_country' => '123', 'en' => 'Kyrgyzstan', 'fr' => 'Kirghizistan', 'es' => 'Kirguistán'),
    array('id_country' => '124', 'en' => 'Laos', 'fr' => 'Laos', 'es' => 'Laos'),
    array('id_country' => '125', 'en' => 'Latvia', 'fr' => 'Lettonie', 'es' => 'Letonia'),
    array('id_country' => '126', 'en' => 'Lebanon', 'fr' => 'Liban', 'es' => 'Líbano'),
    array('id_country' => '127', 'en' => 'Lesotho', 'fr' => 'Lesotho', 'es' => 'Lesotho'),
    array('id_country' => '128', 'en' => 'Liberia', 'fr' => 'Libéria', 'es' => 'Liberia'),
    array('id_country' => '129', 'en' => 'Libya', 'fr' => 'Libyenne, Jamahiriya Arabe', 'es' => 'Libia'),
    array('id_country' => '130', 'en' => 'Liechtenstein', 'fr' => 'Liechtenstein', 'es' => 'Liechtenstein'),
    array('id_country' => '131', 'en' => 'Lithuania', 'fr' => 'Lituanie', 'es' => 'Lituania'),
    array('id_country' => '132', 'en' => 'Macau', 'fr' => 'Macao', 'es' => 'Macao'),
    array('id_country' => '133', 'en' => 'Macedonia', 'fr' => 'Macédoine', 'es' => 'Macedonia'),
    array('id_country' => '134', 'en' => 'Madagascar', 'fr' => 'Madagascar', 'es' => 'Madagascar'),
    array('id_country' => '135', 'en' => 'Malawi', 'fr' => 'Malawi', 'es' => 'Malawi'),
    array('id_country' => '136', 'en' => 'Malaysia', 'fr' => 'Malaisie', 'es' => 'Malasia'),
    array('id_country' => '137', 'en' => 'Maldives', 'fr' => 'Maldives', 'es' => 'Maldivas'),
    array('id_country' => '138', 'en' => 'Mali', 'fr' => 'Mali', 'es' => 'Malí'),
    array('id_country' => '139', 'en' => 'Malta', 'fr' => 'Malte', 'es' => 'Malta'),
    array('id_country' => '140', 'en' => 'Marshall Islands', 'fr' => 'Marshall, Îles', 'es' => 'Marshall, Islas'),
    array('id_country' => '141', 'en' => 'Martinique', 'fr' => 'Martinique', 'es' => 'Martinica'),
    array('id_country' => '142', 'en' => 'Mauritania', 'fr' => 'Mauritanie', 'es' => 'Mauritania'),
    array('id_country' => '143', 'en' => 'Hungary', 'fr' => 'Hongrie', 'es' => 'Hungría'),
    array('id_country' => '144', 'en' => 'Mayotte', 'fr' => 'Mayotte', 'es' => 'Mayotte'),
    array('id_country' => '145', 'en' => 'Mexico', 'fr' => 'Mexique', 'es' => 'México'),
    array('id_country' => '146', 'en' => 'Micronesia', 'fr' => 'Micronésie', 'es' => 'Micronesia'),
    array('id_country' => '147', 'en' => 'Moldova', 'fr' => 'Moldova', 'es' => 'Moldavia'),
    array('id_country' => '148', 'en' => 'Monaco', 'fr' => 'Monaco', 'es' => 'Mónaco'),
    array('id_country' => '149', 'en' => 'Mongolia', 'fr' => 'Mongolie', 'es' => 'Mongolia'),
    array('id_country' => '150', 'en' => 'Montenegro', 'fr' => 'Monténégro', 'es' => 'Montenegro'),
    array('id_country' => '151', 'en' => 'Montserrat', 'fr' => 'Montserrat', 'es' => 'Montserrat'),
    array('id_country' => '152', 'en' => 'Morocco', 'fr' => 'Maroc', 'es' => 'Marruecos'),
    array('id_country' => '153', 'en' => 'Mozambique', 'fr' => 'Mozambique', 'es' => 'Mozambique'),
    array('id_country' => '154', 'en' => 'Namibia', 'fr' => 'Namibie', 'es' => 'Namibia'),
    array('id_country' => '155', 'en' => 'Nauru', 'fr' => 'Nauru', 'es' => 'Nauru'),
    array('id_country' => '156', 'en' => 'Nepal', 'fr' => 'Népal', 'es' => 'Nepal'),
    array('id_country' => '157', 'en' => 'Netherlands Antilles', 'fr' => 'Antilles Néerlandaises', 'es' => 'Antillas Neerlandesas'),
    array('id_country' => '158', 'en' => 'New Caledonia', 'fr' => 'Nouvelle-Calédonie', 'es' => 'Nueva Caledonia'),
    array('id_country' => '159', 'en' => 'Nicaragua', 'fr' => 'Nicaragua', 'es' => 'Nicaragua'),
    array('id_country' => '160', 'en' => 'Niger', 'fr' => 'Niger', 'es' => 'Níger'),
    array('id_country' => '161', 'en' => 'Niue', 'fr' => 'Niué', 'es' => 'Niue'),
    array('id_country' => '162', 'en' => 'Norfolk Island', 'fr' => 'Norfolk, Île', 'es' => 'Norfolk Island'),
    array('id_country' => '163', 'en' => 'Northern Mariana Islands', 'fr' => 'Mariannes du Nord, Îles', 'es' => 'Islas Marianas del Norte'),
    array('id_country' => '164', 'en' => 'Oman', 'fr' => 'Oman', 'es' => 'Omán'),
    array('id_country' => '165', 'en' => 'Pakistan', 'fr' => 'Pakistan', 'es' => 'Pakistán'),
    array('id_country' => '166', 'en' => 'Palau', 'fr' => 'Palaos', 'es' => 'Palau'),
    array('id_country' => '167', 'en' => 'Palestinian Territories', 'fr' => 'Palestinien Occupé, Territoire', 'es' => 'Territorios Palestinos'),
    array('id_country' => '168', 'en' => 'Panama', 'fr' => 'Panama', 'es' => 'Panamá'),
    array('id_country' => '169', 'en' => 'Papua New Guinea', 'fr' => 'Papouasie-Nouvelle-Guinée', 'es' => 'Papua Nueva Guinea'),
    array('id_country' => '170', 'en' => 'Paraguay', 'fr' => 'Paraguay', 'es' => 'Paraguay'),
    array('id_country' => '171', 'en' => 'Peru', 'fr' => 'Pérou', 'es' => 'Perú'),
    array('id_country' => '172', 'en' => 'Philippines', 'fr' => 'Philippines', 'es' => 'Filipinas'),
    array('id_country' => '173', 'en' => 'Pitcairn', 'fr' => 'Pitcairn', 'es' => 'Pitcairn'),
    array('id_country' => '174', 'en' => 'Puerto Rico', 'fr' => 'Porto Rico', 'es' => 'Puerto Rico'),
    array('id_country' => '175', 'en' => 'Qatar', 'fr' => 'Qatar', 'es' => 'Qatar'),
    array('id_country' => '176', 'en' => 'Reunion Island', 'fr' => 'Réunion, Île de la', 'es' => 'Reunión, Isla de la'),
    array('id_country' => '177', 'en' => 'Russian Federation', 'fr' => 'Russie, Fédération de', 'es' => 'Rusia, Federación de'),
    array('id_country' => '178', 'en' => 'Rwanda', 'fr' => 'Rwanda', 'es' => 'Rwanda'),
    array('id_country' => '179', 'en' => 'Saint Barthelemy', 'fr' => 'Saint-Barthélemy', 'es' => 'San Bartolomé'),
    array('id_country' => '180', 'en' => 'Saint Kitts and Nevis', 'fr' => 'Saint-Kitts-et-Nevis', 'es' => 'Saint Kitts y Nevis'),
    array('id_country' => '181', 'en' => 'Saint Lucia', 'fr' => 'Sainte-Lucie', 'es' => 'Santa Lucía'),
    array('id_country' => '182', 'en' => 'Saint Martin', 'fr' => 'Saint-Martin', 'es' => 'Saint Martin'),
    array('id_country' => '183', 'en' => 'Saint Pierre and Miquelon', 'fr' => 'Saint-Pierre-et-Miquelon', 'es' => 'San Pedro y Miquelón'),
    array('id_country' => '184', 'en' => 'Saint Vincent and the Grenadines', 'fr' => 'Saint-Vincent-et-Les Grenadines', 'es' => 'San Vicente y las Granadinas'),
    array('id_country' => '185', 'en' => 'Samoa', 'fr' => 'Samoa', 'es' => 'Samoa'),
    array('id_country' => '186', 'en' => 'San Marino', 'fr' => 'Saint-Marin', 'es' => 'San Marino'),
    array('id_country' => '187', 'en' => 'São Tomé and Príncipe', 'fr' => 'Sao Tomé-et-Principe', 'es' => 'Santo Tomé y Príncipe'),
    array('id_country' => '188', 'en' => 'Saudi Arabia', 'fr' => 'Arabie Saoudite', 'es' => 'Arabia Saudita'),
    array('id_country' => '189', 'en' => 'Senegal', 'fr' => 'Sénégal', 'es' => 'Senegal'),
    array('id_country' => '190', 'en' => 'Serbia', 'fr' => 'Serbie', 'es' => 'Serbia'),
    array('id_country' => '191', 'en' => 'Seychelles', 'fr' => 'Seychelles', 'es' => 'Seychelles'),
    array('id_country' => '192', 'en' => 'Sierra Leone', 'fr' => 'Sierra Leone', 'es' => 'Sierra Leona'),
    array('id_country' => '193', 'en' => 'Slovenia', 'fr' => 'Slovénie', 'es' => 'Eslovenia'),
    array('id_country' => '194', 'en' => 'Solomon Islands', 'fr' => 'Salomon, Îles', 'es' => 'Salomón, Islas'),
    array('id_country' => '195', 'en' => 'Somalia', 'fr' => 'Somalie', 'es' => 'Somalia'),
    array('id_country' => '196', 'en' => 'South Georgia and the South Sandwich Islands', 'fr' => 'Géorgie du Sud et les Îles Sandwich du Sud', 'es' => 'Georgia del Sur e Islas Sandwich del Sur'),
    array('id_country' => '197', 'en' => 'Sri Lanka', 'fr' => 'Sri Lanka', 'es' => 'Sri Lanka'),
    array('id_country' => '198', 'en' => 'Sudan', 'fr' => 'Soudan', 'es' => 'Sudán'),
    array('id_country' => '199', 'en' => 'Suriname', 'fr' => 'Suriname', 'es' => 'Suriname'),
    array('id_country' => '200', 'en' => 'Svalbard and Jan Mayen', 'fr' => 'Svalbard et Île Jan Mayen', 'es' => 'Svalbard y Jan Mayen'),
    array('id_country' => '201', 'en' => 'Swaziland', 'fr' => 'Swaziland', 'es' => 'Swazilandia'),
    array('id_country' => '202', 'en' => 'Syria', 'fr' => 'Syrienne', 'es' => 'Siria'),
    array('id_country' => '203', 'en' => 'Taiwan', 'fr' => 'Taïwan', 'es' => 'Taiwán'),
    array('id_country' => '204', 'en' => 'Tajikistan', 'fr' => 'Tadjikistan', 'es' => 'Tayikistán'),
    array('id_country' => '205', 'en' => 'Tanzania', 'fr' => 'Tanzanie', 'es' => 'Tanzania'),
    array('id_country' => '206', 'en' => 'Thailand', 'fr' => 'Thaïlande', 'es' => 'Tailandia'),
    array('id_country' => '207', 'en' => 'Tokelau', 'fr' => 'Tokelau', 'es' => 'Tokelau'),
    array('id_country' => '208', 'en' => 'Tonga', 'fr' => 'Tonga', 'es' => 'Tonga'),
    array('id_country' => '209', 'en' => 'Trinidad and Tobago', 'fr' => 'Trinité-et-Tobago', 'es' => 'Trinidad y Tobago'),
    array('id_country' => '210', 'en' => 'Tunisia', 'fr' => 'Tunisie', 'es' => 'Túnez'),
    array('id_country' => '211', 'en' => 'Turkey', 'fr' => 'Turquie', 'es' => 'Turquía'),
    array('id_country' => '212', 'en' => 'Turkmenistan', 'fr' => 'Turkménistan', 'es' => 'Turkmenistán'),
    array('id_country' => '213', 'en' => 'Turks and Caicos Islands', 'fr' => 'Turks et Caiques, Îles', 'es' => 'Islas Turcas y Caicos'),
    array('id_country' => '214', 'en' => 'Tuvalu', 'fr' => 'Tuvalu', 'es' => 'Tuvalu'),
    array('id_country' => '215', 'en' => 'Uganda', 'fr' => 'Ouganda', 'es' => 'Uganda'),
    array('id_country' => '216', 'en' => 'Ukraine', 'fr' => 'Ukraine', 'es' => 'Ucrania'),
    array('id_country' => '217', 'en' => 'United Arab Emirates', 'fr' => 'Émirats Arabes Unis', 'es' => 'Emiratos Árabes Unidos'),
    array('id_country' => '218', 'en' => 'Uruguay', 'fr' => 'Uruguay', 'es' => 'Uruguay'),
    array('id_country' => '219', 'en' => 'Uzbekistan', 'fr' => 'Ouzbékistan', 'es' => 'Uzbekistán'),
    array('id_country' => '220', 'en' => 'Vanuatu', 'fr' => 'Vanuatu', 'es' => 'Vanuatu'),
    array('id_country' => '221', 'en' => 'Venezuela', 'fr' => 'Venezuela', 'es' => 'Venezuela'),
    array('id_country' => '222', 'en' => 'Vietnam', 'fr' => 'Vietnam', 'es' => 'Vietnam'),
    array('id_country' => '223', 'en' => 'Virgin Islands (British)', 'fr' => 'Îles Vierges Britanniques', 'es' => 'Islas Vírgenes (Británicas)'),
    array('id_country' => '224', 'en' => 'Virgin Islands (U.S.)', 'fr' => 'Îles Vierges des États-Unis', 'es' => 'Islas Vírgenes (EE.UU.)'),
    array('id_country' => '225', 'en' => 'Wallis and Futuna', 'fr' => 'Wallis et Futuna', 'es' => 'Wallis y Futuna'),
    array('id_country' => '226', 'en' => 'Western Sahara', 'fr' => 'Sahara Occidental', 'es' => 'Sáhara Occidental'),
    array('id_country' => '227', 'en' => 'Yemen', 'fr' => 'Yémen', 'es' => 'Yemen'),
    array('id_country' => '228', 'en' => 'Zambia', 'fr' => 'Zambie', 'es' => 'Zambia'),
    array('id_country' => '229', 'en' => 'Zimbabwe', 'fr' => 'Zimbabwe', 'es' => 'Zimbabwe'),
    array('id_country' => '230', 'en' => 'Albania', 'fr' => 'Albanie', 'es' => 'Albania'),
    array('id_country' => '231', 'en' => 'Afghanistan', 'fr' => 'Afghanistan', 'es' => 'Afganistán'),
    array('id_country' => '232', 'en' => 'Antarctica', 'fr' => 'Antarctique', 'es' => 'Antártida'),
    array('id_country' => '233', 'en' => 'Bosnia and Herzegovina', 'fr' => 'Bosnie-Herzégovine', 'es' => 'Bosnia y Herzegovina'),
    array('id_country' => '234', 'en' => 'Bouvet Island', 'fr' => 'Bouvet, Île', 'es' => 'Isla Bouvet'),
    array('id_country' => '235', 'en' => 'British Indian Ocean Territory', 'fr' => 'Océan Indien, Territoire Britannique de L\'', 'es' => 'British Indian Ocean Territory'),
    array('id_country' => '236', 'en' => 'Bulgaria', 'fr' => 'Bulgarie', 'es' => 'Bulgaria'),
    array('id_country' => '237', 'en' => 'Cayman Islands', 'fr' => 'Caïmans, Îles', 'es' => 'Caimán, Islas'),
    array('id_country' => '238', 'en' => 'Christmas Island', 'fr' => 'Christmas, Île', 'es' => 'Navidad, Isla de'),
    array('id_country' => '239', 'en' => 'Cocos (Keeling) Islands', 'fr' => 'Cocos (Keeling), Îles', 'es' => 'Cocos (Keeling), Islas'),
    array('id_country' => '240', 'en' => 'Cook Islands', 'fr' => 'Cook, Îles', 'es' => 'Cook, Islas'),
    array('id_country' => '241', 'en' => 'French Guiana', 'fr' => 'Guyane Française', 'es' => 'Francés Guayana'),
    array('id_country' => '242', 'en' => 'French Polynesia', 'fr' => 'Polynésie Française', 'es' => 'Polinesia francés'),
    array('id_country' => '243', 'en' => 'French Southern Territories', 'fr' => 'Terres Australes Françaises', 'es' => 'Territorios del sur francés'),
    array('id_country' => '244', 'en' => 'Åland Islands', 'fr' => 'Åland, Îles', 'es' => 'Islas Åland'),
);

if ($langs = Language::getLanguages(false)) {
    foreach ($langs as $lang) {
        foreach ($country_lang as $country) {
            if (isset($country[$lang['iso_code']])) {
                $name = $country[$lang['iso_code']];
            } elseif ('ag' == $lang['iso_code'] || 'cb' == $lang['iso_code'] || 'mx' == $lang['iso_code']) {
                $name = $country['es'];
            } else {
                $name = $country['en'];
            }

            $sql[] = 'INSERT INTO `'._DB_PREFIX_.'rg_locationdetection_country_lang` (`id_country`, `id_lang`, `name`) VALUES (\''.$country['id_country'].'\', \''.$lang['id_lang'].'\', \''.pSQL($name).'\');';
        }
    }
}

$sql[] = 'CREATE TABLE IF NOT EXISTS `'._DB_PREFIX_.'rg_locationdetection_redirection` (
    `id_redirection` int(10) NOT NULL AUTO_INCREMENT,
    `id_shop_group` int(11) unsigned NOT NULL DEFAULT \'1\',
    `id_shop` int(11) unsigned NOT NULL DEFAULT \'1\',
    `url` varchar(255) NOT NULL,
    `quantity` int(10) unsigned NOT NULL DEFAULT \'0\',
    `full_path` tinyint(1) unsigned NOT NULL DEFAULT \'0\',
    `use_popup` tinyint(1) unsigned NOT NULL DEFAULT \'1\',
    `active` tinyint(1) unsigned NOT NULL DEFAULT \'1\',
    PRIMARY KEY  (`id_redirection`),
    KEY `id_shop_group` (`id_shop_group`),
    KEY `id_shop` (`id_shop`)
) ENGINE='._MYSQL_ENGINE_.' DEFAULT CHARSET=utf8;';

$sql[] = 'CREATE TABLE IF NOT EXISTS `'._DB_PREFIX_.'rg_locationdetection_redirection_lang` (
    `id_redirection` int(10) unsigned NOT NULL,
    `id_lang` int(10) unsigned NOT NULL,
    `popup` text NOT NULL,
    PRIMARY KEY (`id_redirection`,`id_lang`)
) ENGINE='._MYSQL_ENGINE_.' DEFAULT CHARSET=utf8;';

$sql[] = 'CREATE TABLE IF NOT EXISTS `'._DB_PREFIX_.'rg_locationdetection_redirection_country` (
    `id_redirection` int(10) unsigned NOT NULL,
    `id_country` int(10) unsigned NOT NULL,
    PRIMARY KEY (`id_redirection`, `id_country`)
) ENGINE='._MYSQL_ENGINE_.' DEFAULT CHARSET=utf8;';

$sql[] = 'CREATE TABLE IF NOT EXISTS `'._DB_PREFIX_.'rg_locationdetection_infobar` (
    `id_infobar` int(10) NOT NULL AUTO_INCREMENT,
    `id_shop_group` int(11) unsigned NOT NULL DEFAULT \'1\',
    `id_shop` int(11) unsigned NOT NULL DEFAULT \'1\',
    `width` varchar(12) DEFAULT NULL,
    `height` varchar(12) DEFAULT NULL,
    `background` varchar(7) DEFAULT NULL,
    `border_size` varchar(12) DEFAULT NULL,
    `border_color` varchar(7) DEFAULT NULL,
    `close_button_color` varchar(7) DEFAULT NULL,
    `position` varchar(6) NOT NULL,
    `static` tinyint(1) unsigned NOT NULL DEFAULT \'0\',
    `custom_css` text DEFAULT NULL,
    `active` tinyint(1) unsigned NOT NULL DEFAULT \'1\',
    PRIMARY KEY  (`id_infobar`),
    KEY `id_shop_group` (`id_shop_group`),
    KEY `id_shop` (`id_shop`)
) ENGINE='._MYSQL_ENGINE_.' DEFAULT CHARSET=utf8;';

$sql[] = 'CREATE TABLE IF NOT EXISTS `'._DB_PREFIX_.'rg_locationdetection_infobar_lang` (
    `id_infobar` int(10) unsigned NOT NULL,
    `id_lang` int(10) unsigned NOT NULL,
    `content` text NOT NULL,
    PRIMARY KEY (`id_infobar`,`id_lang`)
) ENGINE='._MYSQL_ENGINE_.' DEFAULT CHARSET=utf8;';

$sql[] = 'CREATE TABLE IF NOT EXISTS `'._DB_PREFIX_.'rg_locationdetection_infobar_country` (
    `id_infobar` int(10) unsigned NOT NULL,
    `id_country` int(10) unsigned NOT NULL,
    PRIMARY KEY (`id_infobar`, `id_country`)
) ENGINE='._MYSQL_ENGINE_.' DEFAULT CHARSET=utf8;';

foreach ($sql as $query) {
    if (false == Db::getInstance()->execute($query)) {
        return false;
    }
}
