<?php
/**
* 2007-2023 PrestaShop
*
* deliveryorderautoupdate
*
*  @author    Helloshop <modules@helloshop.com>
*  @copyright 2007-2023 Helloshop
*  @license   license http://www.gnu.org/licenses/gpl-2.0.html GNU/GPL
*  @Website: http://www.Helloshop.com
*/

if (!defined('_PS_VERSION_')) {
    exit;
}

function upgrade_module_1_3_0()
{
    $query = array();
    $date = pSQL(Date("Y-m-d"));
    if (check_index() == null) {
        $query[]  = 'CREATE TABLE IF NOT EXISTS `'._DB_PREFIX_.'hl_tracking_history` (
				  `id` int(10) NOT NULL AUTO_INCREMENT,
				  `id_order` int(10) NOT NULL,
				  `hl_carrier` int(11) NOT NULL,
				  `method` tinyint(1) NOT NULL,
				  `success_response` tinyint(1) NOT NULL,
				  `event_code` tinyint(1) NOT NULL,
				  `carrier_response` varchar(128) NOT NULL,
				  `step_date` datetime NOT NULL,
				  `email_sent` tinyint(1) NOT NULL,
				  `date_add` datetime NOT NULL,
				  PRIMARY KEY (`id`)
				) ENGINE='._MYSQL_ENGINE_.'  DEFAULT CHARSET=utf8';
        $query[]  = 'ALTER TABLE `'._DB_PREFIX_.'hl_carrier` ADD `method` TINYINT(1) NOT NULL AFTER `url`;';
        $query[]  = 'ALTER TABLE `'._DB_PREFIX_.'hl_carrier` ADD `user` VARCHAR(64) NOT NULL AFTER `method`;';
        $query[]  = 'ALTER TABLE `'._DB_PREFIX_.'hl_carrier` ADD `password` VARCHAR(64) NOT NULL AFTER `user`';
        $query[]  = 'INSERT INTO '._DB_PREFIX_.'configuration
        (name, value, id_shop, id_shop_group, date_add, date_add)
        value ("updatestatusversion", 1.3.0, 1, 1, "'.$date.'", "'.$date.'")';
        foreach ($query as $q) {
            Db::getInstance()->execute($q);
        }
        //insertData();
        return true;
    }
    return false;
}

function check_index()
{
    $indexes = Db::getInstance()->getRow(
        'SELECT value FROM '._DB_PREFIX_.'configuration WHERE name like "updatestatusversion"'
    );
    return ($indexes['value']);
}
function insertData()
{
    $sql = array();

    $sql[] = "REPLACE INTO `"._DB_PREFIX_."hl_carrier`
    (`id`, `active`, `name`, `url`, `method`, `user_label`, `user`, `password_label`, `password`) VALUES

            (14, 0, 'GLS Italy', '', 0, '', '', '', ''),
            (15, 0, 'FedEx', '', 0, '', '', '', ''),
            (16, 0, 'UPS', '', 0, '', '', '', ''),
            (17, 0, 'DHL Express', '', 0, '', '', '', ''),
            (18, 0, 'DHL International', '', 0, '', '', '', ''),
            (19, 0, 'DHL Express (Piece ID)', '', 0, '', '', '', ''),
            (20, 0, 'DHL International', '', 0, '', '', '', ''),
            (21, 0, 'USPS', '', 0, '', '', '', ''),
            (22, 0, 'UPS Mail Innovations', '', 0, '', '', '', ''),
            (23, 0, 'UPS MI', '', 0, '', '', '', ''),
            (24, 0, 'TNT', '', 0, '', '', '', ''),
            (25, 0, 'TNT Express', '', 0, '', '', '', ''),
            (26, 0, 'TNT Reference', '', 0, '', '', '', ''),
            (27, 0, 'TNT consignment reference', '', 0, '', '', '', ''),
            (28, 0, 'DPD', '', 0, '', '', '', ''),
            (29, 0, 'Dynamic Parcel Distribution', '', 0, '', '', '', ''),
            (30, 0, 'Aramex', '', 0, '', '', '', ''),
            (31, 0, 'DHL eCommerce', '', 0, '', '', '', ''),
            (32, 0, 'DHL Global Mail', '', 0, '', '', '', ''),
            (33, 0, 'DSV', '', 0, '', '', '', ''),
            (34, 0, 'DHL Global Forwarding', '', 0, '', '', '', ''),
            (35, 0, 'DHL Logistics', '', 0, '', '', '', ''),
            (36, 0, 'Echo', '', 0, '', '', '', ''),
            (37, 0, 'Echo Global Logistics', '', 0, '', '', '', ''),
            (38, 0, 'UPS Freight', '', 0, '', '', '', ''),
            (39, 0, 'UPS LTL and Truckload', '', 0, '', '', '', ''),
            (40, 0, 'FedEx Freight', '', 0, '', '', '', ''),
            (41, 0, 'FedEx LTL', '', 0, '', '', '', ''),
            (42, 0, 'Canada Post', '', 0, '', '', '', ''),
            (43, 0, 'Canada CANPostes Canada', '', 0, '', '', '', ''),
            (44, 0, 'Canpar Courier', '', 0, '', '', '', ''),
            (45, 0, 'Canada CANTransForce', '', 0, '', '', '', ''),
            (46, 0, 'Purolator', '', 0, '', '', '', ''),
            (47, 0, 'Purolator Freight', '', 0, '', '', '', ''),
            (48, 0, 'APC Postal Logistics', '', 0, '', '', '', ''),
            (49, 0, 'APC-PLI', '', 0, '', '', '', ''),
            (50, 0, 'OnTrac', '', 0, '', '', '', ''),
            (51, 0, 'OnTrac Shipping', '', 0, '', '', '', ''),
            (52, 0, 'YRC', '', 0, '', '', '', ''),
            (53, 0, 'YRC Freight', '', 0, '', '', '', ''),
            (54, 0, 'Asendia USA', '', 0, '', '', '', ''),
            (55, 0, 'Brokers Worldwide', '', 0, '', '', '', ''),
            (56, 0, 'Ensenda', '', 0, '', '', '', ''),
            (57, 0, 'Newgistics', '', 0, '', '', '', ''),
            (58, 0, 'LaserShip', '', 0, '', '', '', ''),
            (59, 0, 'LaserShip', '', 0, '', '', '', ''),
            (60, 0, 'Expeditors', '', 0, '', '', '', ''),
            (61, 0, 'i-parcel', '', 0, '', '', '', ''),
            (62, 0, 'ABF Freight', '', 0, '', '', '', ''),
            (63, 0, 'Arkansas Best Corporation', '', 0, '', '', '', ''),
            (64, 0, 'Old Dominion Freight Line', '', 0, '', '', '', ''),
            (65, 0, 'ODFL', '', 0, '', '', '', ''),
            (66, 0, 'Con-way Freight', '', 0, '', '', '', ''),
            (67, 0, 'Conway', '', 0, '', '', '', ''),
            (68, 0, 'Estes', '', 0, '', '', '', ''),
            (69, 0, 'Estes Express Lines', '', 0, '', '', '', ''),
            (70, 0, 'RL Carriers', '', 0, '', '', '', ''),
            (71, 0, 'R+L Carriers', '', 0, '', '', '', ''),
            (72, 0, 'Direct Link', '', 0, '', '', '', ''),
            (73, 0, 'Direct Link', '', 0, '', '', '', ''),
            (74, 0, 'International Seur', '', 0, '', '', '', ''),
            (75, 0, 'SEUR Internacional', '', 0, '', '', '', ''),
            (76, 0, 'GLS', '', 0, '', '', '', ''),
            (77, 0, 'DHL Benelux', '', 0, '', '', '', ''),
            (78, 0, 'DHL TrackNet Benelux', '', 0, '', '', '', ''),
            (79, 0, 'PostNord Logistics', '', 0, '', '', '', ''),
            (80, 0, 'Posten Norden', '', 0, '', '', '', ''),
            (81, 0, 'Royal Mail', '', 0, '', '', '', ''),
            (82, 0, 'Parcel Force', '', 0, '', '', '', ''),
            (83, 0, 'Parcelforce UK', '', 0, '', '', '', ''),
            (84, 0, 'FedEx UK', '', 0, '', '', '', ''),
            (85, 0, 'DPD UK', '', 0, '', '', '', ''),
            (86, 0, 'Dynamic Parcel Distribution UK', '', 0, '', '', '', ''),
            (87, 0, 'Collect+', '', 0, '', '', '', ''),
            (88, 0, 'Collect Plus UK', '', 0, '', '', '', ''),
            (89, 0, 'SkyNet Worldwide Express', '', 0, '', '', '', ''),
            (90, 0, 'Skynetwwe', '', 0, '', '', '', ''),
            (91, 0, 'Skynet Worldwide Express UK', '', 0, '', '', '', ''),
            (92, 0, 'Skynet UK', '', 0, '', '', '', ''),
            (93, 0, 'TNT UK', '', 0, '', '', '', ''),
            (94, 0, 'TNT United Kingdom', '', 0, '', '', '', ''),
            (95, 0, 'TNT UK Reference', '', 0, '', '', '', ''),
            (96, 0, 'TNT UK consignment reference', '', 0, '', '', '', ''),
            (97, 0, 'Interlink Express', '', 0, '', '', '', ''),
            (98, 0, 'Interlink UK', '', 0, '', '', '', ''),
            (99, 0, 'Interlink Express Reference', '', 0, '', '', '', ''),
            (100, 0, 'UK Mail', '', 0, '', '', '', ''),
            (101, 0, 'Business Post Group', '', 0, '', '', '', ''),
            (102, 0, 'Yodel Domestic', '', 0, '', '', '', ''),
            (103, 0, 'Yodel International', '', 0, '', '', '', ''),
            (104, 0, 'Home Delivery Network, HDNL', '', 0, '', '', '', ''),
            (105, 0, 'Hermesworld', '', 0, '', '', '', ''),
            (106, 0, 'Hermes-europe UK', '', 0, '', '', '', ''),
            (107, 0, 'myHermes UK', '', 0, '', '', '', ''),
            (108, 0, 'Norsk Global', '', 0, '', '', '', ''),
            (109, 0, 'Norsk European Wholesale', '', 0, '', '', '', ''),
            (110, 0, 'Panther', '', 0, '', '', '', ''),
            (111, 0, 'Panther Group UK', '', 0, '', '', '', ''),
            (112, 0, 'Deltec Courier', '', 0, '', '', '', ''),
            (113, 0, 'Deltec Interntional Courier', '', 0, '', '', '', ''),
            (114, 0, 'XDP Express', '', 0, '', '', '', ''),
            (115, 0, 'XDP UK', '', 0, '', '', '', ''),
            (116, 0, 'TrakPak', '', 0, '', '', '', ''),
            (117, 0, 'bpost international P2P Mailing Trak Pak', '', 0, '', '', '', ''),
            (118, 0, 'XDP Express Reference', '', 0, '', '', '', ''),
            (119, 0, 'XDP UK', '', 0, '', '', '', ''),
            (120, 0, 'An Post', '', 0, '', '', '', ''),
            (121, 0, 'Ireland Post', '', 0, '', '', '', ''),
            (122, 0, 'DPD Ireland', '', 0, '', '', '', ''),
            (123, 0, 'Ireland IRLDPD ie', '', 0, '', '', '', ''),
            (124, 0, 'Fastway Ireland', '', 0, '', '', '', ''),
            (125, 0, 'Ireland IRLFastway Couriers', '', 0, '', '', '', ''),
            (126, 0, 'Nightline', '', 0, '', '', '', ''),
            (127, 0, 'Ireland IRL', '', 0, '', '', '', ''),
            (128, 0, 'Tuffnells Parcels Express', '', 0, '', '', '', ''),
            (129, 0, 'Arrow XL', '', 0, '', '', '', ''),
            (130, 0, 'Yodel XL', '', 0, '', '', '', ''),
            (131, 0, 'Deutsche Post Mail', '', 0, '', '', '', ''),
            (132, 0, 'Germany DEUdpdhl', '', 0, '', '', '', ''),
            (133, 0, 'Deutsche Post DHL', '', 0, '', '', '', ''),
            (134, 0, 'DHL Germany', '', 0, '', '', '', ''),
            (135, 0, 'Hermes Germany', '', 0, '', '', '', ''),
            (136, 0, 'myhermes.de, Hermes Logistik Gruppe Deutschland', '', 0, '', '', '', ''),
            (137, 0, 'DPD Germany', '', 0, '', '', '', ''),
            (138, 0, 'DPD Germany', '', 0, '', '', '', ''),
            (139, 0, 'Asendia Germany', '', 0, '', '', '', ''),
            (140, 0, 'Germany DEUAsendia De', '', 0, '', '', '', ''),
            (141, 0, 'DHL 2-Mann-Handling', '', 0, '', '', '', ''),
            (142, 0, 'DHL Deliver IT', '', 0, '', '', '', ''),
            (143, 0, 'Austrian Post (Registered)', '', 0, '', '', '', ''),
            (144, 0, 'Austria AUTÖsterreichische Post AG', '', 0, '', '', '', ''),
            (145, 0, 'Austrian Post (Express)', '', 0, '', '', '', ''),
            (146, 0, 'Swiss Post', '', 0, '', '', '', ''),
            (147, 0, 'Switzerland CHELa Poste Suisse, Die Schweizerische Post, Die Post', '', 0, '', '', '', ''),
            (148, 0, 'Correos de España', '', 0, '', '', '', ''),
            (149, 0, 'Spain Post, ChronoExpress', '', 0, '', '', '', ''),
            (150, 0, 'Correos Express', '', 0, '', '', '', ''),
            (151, 0, 'NACEX Spain', '', 0, '', '', '', ''),
            (152, 0, 'NACEX Logista', '', 0, '', '', '', ''),
            (153, 0, 'Spanish Seur', '', 0, '', '', '', ''),
            (154, 0, 'SEUR', '', 0, '', '', '', ''),
            (155, 0, 'ASM', '', 0, '', '', '', ''),
            (156, 0, 'Asm-Red', '', 0, '', '', '', ''),
            (157, 0, 'MRW', '', 0, '', '', '', ''),
            (158, 0, 'MRW Spain', '', 0, '', '', '', ''),
            (159, 0, 'Envialia', '', 0, '', '', '', ''),
            (160, 0, 'Envialia Spain', '', 0, '', '', '', ''),
            (161, 0, 'Redur Spain', '', 0, '', '', '', ''),
            (162, 0, 'Eurodis', '', 0, '', '', '', ''),
            (163, 0, 'Packlink', '', 0, '', '', '', ''),
            (164, 0, 'Packlink Spain', '', 0, '', '', '', ''),
            (165, 0, 'DHL Spain Domestic', '', 0, '', '', '', ''),
            (166, 0, 'DHL España', '', 0, '', '', '', ''),
            (167, 0, 'Magyar Posta', '', 0, '', '', '', ''),
            (168, 0, 'Hungary HUNHungarian Post', '', 0, '', '', '', ''),
            (169, 0, 'Exapaq', '', 0, '', '', '', ''),
            (170, 0, 'DPD France', '', 0, '', '', '', ''),
            (171, 0, 'Portugal CTT', '', 0, '', '', '', ''),
            (172, 0, 'Correios de Portugal', '', 0, '', '', '', ''),
            (173, 0, 'Chronopost Portugal', '', 0, '', '', '', ''),
            (174, 0, 'Chronopost pt', '', 0, '', '', '', ''),
            (175, 0, 'Portugal Seur', '', 0, '', '', '', ''),
            (176, 0, 'Adicional Logistics', '', 0, '', '', '', ''),
            (177, 0, 'Colissimo', '', 0, '', '', '', ''),
            (178, 0, 'Chronopost France', '', 0, '', '', '', ''),
            (179, 0, 'TNT France', '', 0, '', '', '', ''),
            (180, 0, 'TNT Express FR', '', 0, '', '', '', ''),
            (181, 0, 'GEODIS - Distribution & Express', '', 0, '', '', '', ''),
            (182, 0, 'Geodiscalberson', '', 0, '', '', '', ''),
            (183, 0, 'Bert Transport', '', 0, '', '', '', ''),
            (184, 0, 'Teliway SIC Express', '', 0, '', '', '', ''),
            (185, 0, 'Prevote', '', 0, '', '', '', ''),
            (186, 0, 'Geodis E-space', '', 0, '', '', '', ''),
            (187, 0, 'Geodis Distribution & Express', '', 0, '', '', '', ''),
            (188, 0, 'Mondial Relay', '', 0, '', '', '', ''),
            (189, 0, 'PostNL Domestic', '', 0, '', '', '', ''),
            (190, 0, 'PostNL Pakketten, TNT Post Netherlands', '', 0, '', '', '', ''),
            (191, 0, 'PostNL International', '', 0, '', '', '', ''),
            (192, 0, 'Netherlands Post, Spring Global Mail', '', 0, '', '', '', ''),
            (193, 0, 'PostNL International 3S', '', 0, '', '', '', ''),
            (194, 0, 'TNT Post parcel service United Kingdom', '', 0, '', '', '', ''),
            (195, 0, 'DHL Netherlands', '', 0, '', '', '', ''),
            (196, 0, 'DHL Nederlands', '', 0, '', '', '', ''),
            (197, 0, 'GLS Netherlands', '', 0, '', '', '', ''),
            (198, 0, 'DHL Parcel NL', '', 0, '', '', '', ''),
            (199, 0, 'Selektvracht, dhlparcel.nl', '', 0, '', '', '', ''),
            (200, 0, 'TransMission', '', 0, '', '', '', ''),
            (201, 0, 'mijnzending', '', 0, '', '', '', ''),
            (202, 0, 'Belgium Post', '', 0, '', '', '', ''),
            (203, 0, 'bpost, Belgian Post', '', 0, '', '', '', ''),
            (204, 0, 'bpost international', '', 0, '', '', '', ''),
            (205, 0, 'Landmark Global', '', 0, '', '', '', ''),
            (206, 0, 'Posti', '', 0, '', '', '', ''),
            (207, 0, 'Finland Post', '', 0, '', '', '', ''),
            (208, 0, 'Posten Norge / Bring', '', 0, '', '', '', ''),
            (209, 0, 'Norway Post, Norska Posten', '', 0, '', '', '', ''),
            (210, 0, 'Sweden Posten', '', 0, '', '', '', ''),
            (211, 0, 'Denmark DNK,Sweden SWESweden Post, Posten, PostNord', '', 0, '', '', '', ''),
            (212, 0, 'DB Schenker Sweden', '', 0, '', '', '', ''),
            (213, 0, 'Deutsche Bahn', '', 0, '', '', '', ''),
            (214, 0, 'Matkahuolto', '', 0, '', '', '', ''),
            (215, 0, 'Finland FINOy Matkahuolto Ab', '', 0, '', '', '', ''),
            (216, 0, 'Post Danmark', '', 0, '', '', '', ''),
            (217, 0, 'Danske Post', '', 0, '', '', '', ''),
            (218, 0, 'InPost Paczkomaty', '', 0, '', '', '', ''),
            (219, 0, 'Raben Group', '', 0, '', '', '', ''),
            (220, 0, 'myRaben', '', 0, '', '', '', ''),
            (221, 0, 'Italy SDA', '', 0, '', '', '', ''),
            (222, 0, 'SDA Express Courier', '', 0, '', '', '', ''),
            (223, 0, 'DMM Network', '', 0, '', '', '', ''),
            (224, 0, 'dmmnetwork.it', '', 0, '', '', '', ''),
            (225, 0, 'Poste Italiane Paccocelere', '', 0, '', '', '', ''),
            (226, 0, 'Italian Post EMS / Express', '', 0, '', '', '', ''),
            (227, 0, 'Poste Italiane', '', 0, '', '', '', ''),
            (228, 0, 'Italian Post', '', 0, '', '', '', ''),
            (229, 0, 'BRT Bartolini', '', 0, '', '', '', ''),
            (230, 0, 'BRT Corriere Espresso, DPD Italy', '', 0, '', '', '', ''),
            (231, 0, 'FERCAM Logistics & Transport', '', 0, '', '', '', ''),
            (232, 0, 'FERCAM SpA', '', 0, '', '', '', ''),
            (233, 0, 'GLS Italy', '', 0, '', '', '', ''),
            (234, 0, 'GLS Corriere Espresso', '', 0, '', '', '', ''),
            (235, 0, 'SGT Corriere Espresso', '', 0, '', '', '', ''),
            (236, 0, 'SoGeTras Corriere Espresso', '', 0, '', '', '', ''),
            (237, 0, 'TNT Italy', '', 0, '', '', '', ''),
            (238, 0, 'TNT Express IT', '', 0, '', '', '', ''),
            (239, 0, 'Nexive (TNT Post Italy)', '', 0, '', '', '', ''),
            (240, 0, 'Postnl TNT', '', 0, '', '', '', ''),
            (241, 0, 'TNT-Click Italy', '', 0, '', '', '', ''),
            (242, 0, 'TNT Italy', '', 0, '', '', '', ''),
            (243, 0, 'Russian Post', '', 0, '', '', '', ''),
            (244, 0, 'EMS Post RU', '', 0, '', '', '', ''),
            (245, 0, 'Iceland Post', '', 0, '', '', '', ''),
            (246, 0, 'Postur.is, Íslandspóstur', '', 0, '', '', '', ''),
            (247, 0, 'Nova Poshta', '', 0, '', '', '', ''),
            (248, 0, 'Новая Почта', '', 0, '', '', '', ''),
            (249, 0, 'DHL Poland Domestic', '', 0, '', '', '', ''),
            (250, 0, 'DHL Polska', '', 0, '', '', '', ''),
            (251, 0, 'Poczta Polska', '', 0, '', '', '', ''),
            (252, 0, 'Poland POLPoland Post', '', 0, '', '', '', ''),
            (253, 0, 'DPD Poland', '', 0, '', '', '', ''),
            (254, 0, 'Dynamic Parcel Distribution Poland', '', 0, '', '', '', ''),
            (255, 0, 'Siodemka', '', 0, '', '', '', ''),
            (256, 0, 'Siodemka Kurier', '', 0, '', '', '', ''),
            (257, 0, 'FedEx Poland Domestic', '', 0, '', '', '', ''),
            (258, 0, 'Poland POLOPEK', '', 0, '', '', '', ''),
            (259, 0, 'Lietuvos Paštas', '', 0, '', '', '', ''),
            (260, 0, 'Lithuania LTULithuania Post, LP Express', '', 0, '', '', '', ''),
            (261, 0, 'Czech Post', '', 0, '', '', '', ''),
            (262, 0, 'ELTA Hellenic Post', '', 0, '', '', '', ''),
            (263, 0, 'Greece Post', '', 0, '', '', '', ''),
            (264, 0, 'ACS Courier', '', 0, '', '', '', ''),
            (265, 0, 'Geniki Taxydromiki', '', 0, '', '', '', ''),
            (266, 0, 'ΓΕΝΙΚΗ ΤΑΧΥΔΡΟΜΙΚΗ', '', 0, '', '', '', ''),
            (267, 0, 'Speed Couriers', '', 0, '', '', '', ''),
            (268, 0, 'PTT Posta', '', 0, '', '', '', ''),
            (269, 0, 'Turkish Post', '', 0, '', '', '', ''),
            (270, 0, 'Belpost', '', 0, '', '', '', ''),
            (271, 0, 'Belposhta, Белпочта', '', 0, '', '', '', ''),
            (272, 0, 'Bulgarian Posts', '', 0, '', '', '', ''),
            (273, 0, 'Hrvatska Pošta', '', 0, '', '', '', ''),
            (274, 0, 'Croatia Post', '', 0, '', '', '', ''),
            (275, 0, 'Kuehne + Nagel', '', 0, '', '', '', ''),
            (276, 0, 'KN', '', 0, '', '', '', ''),
            (277, 0, 'Poșta Română', '', 0, '', '', '', ''),
            (278, 0, 'Romania Post', '', 0, '', '', '', ''),
            (279, 0, 'Cyprus Post', '', 0, '', '', '', ''),
            (280, 0, 'ΚΥΠΡΙΑΚΑ ΤΑΧΥΔΡΟΜΕΙΑ', '', 0, '', '', '', ''),
            (281, 0, 'UkrPoshta', '', 0, '', '', '', ''),
            (282, 0, 'Укрпошта', '', 0, '', '', '', ''),
            (283, 0, 'S.F. Express', '', 0, '', '', '', ''),
            (284, 0, 'S.F International', '', 0, '', '', '', ''),
            (285, 0, 'DHL Global Mail Asia', '', 0, '', '', '', ''),
            (286, 0, 'DGM Asia', '', 0, '', '', '', ''),
            (287, 0, 'Kerry Express Thailand', '', 0, '', '', '', ''),
            (288, 0, 'Kerry Logistics', '', 0, '', '', '', ''),
            (289, 0, 'Quantium', '', 0, '', '', '', ''),
            (290, 0, 'HDPEX', '', 0, '', '', '', ''),
            (291, 0, 'TGX, Toll Global Express Asia', '', 0, '', '', '', ''),
            (292, 0, 'Omni Parcel', '', 0, '', '', '', ''),
            (293, 0, 'Omni-Channel Logistics (Seko)', '', 0, '', '', '', ''),
            (294, 0, 'China Post', '', 0, '', '', '', ''),
            (295, 0, '中国邮政, ePacket, e-Packet', '', 0, '', '', '', ''),
            (296, 0, 'China EMS', '', 0, '', '', '', ''),
            (297, 0, '中国邮政速递物流', '', 0, '', '', '', ''),
            (298, 0, '4PX', '', 0, '', '', '', ''),
            (299, 0, '递四方', '', 0, '', '', '', ''),
            (300, 0, 'Yanwen', '', 0, '', '', '', ''),
            (301, 0, '燕文物流', '', 0, '', '', '', ''),
            (302, 0, 'SFC Service', '', 0, '', '', '', ''),
            (303, 0, 'EC-Firstclass', '', 0, '', '', '', ''),
            (304, 0, 'ChuKou1, CK1', '', 0, '', '', '', ''),
            (305, 0, 'AuPost China', '', 0, '', '', '', ''),
            (306, 0, '澳邮宝', '', 0, '', '', '', ''),
            (307, 0, 'WeDo Logistics', '', 0, '', '', '', ''),
            (308, 0, '運德物流', '', 0, '', '', '', ''),
            (309, 0, 'PayPal Package', '', 0, '', '', '', ''),
            (310, 0, '贝邮宝', '', 0, '', '', '', ''),
            (311, 0, 'JCEX', '', 0, '', '', '', ''),
            (312, 0, 'JiaCheng, 杭州佳成', '', 0, '', '', '', ''),
            (313, 0, 'WishPost', '', 0, '', '', '', ''),
            (314, 0, 'Wish', '', 0, '', '', '', ''),
            (315, 0, 'STO Express', '', 0, '', '', '', ''),
            (316, 0, 'Shentong Express', '', 0, '', '', '', ''),
            (317, 0, 'Greyhound', '', 0, '', '', '', ''),
            (318, 0, 'Greyhound Package Express', '', 0, '', '', '', ''),
            (319, 0, 'Globegistics Inc.', '', 0, '', '', '', ''),
            (320, 0, 'Post56', '', 0, '', '', '', ''),
            (321, 0, '捷邮快递', '', 0, '', '', '', ''),
            (322, 0, 'Flyt Express', '', 0, '', '', '', ''),
            (323, 0, '飞特物流', '', 0, '', '', '', ''),
            (324, 0, 'DPEX China', '', 0, '', '', '', ''),
            (325, 0, 'DPEX（深圳）国际物流, Toll China', '', 0, '', '', '', ''),
            (326, 0, 'Best Express', '', 0, '', '', '', ''),
            (327, 0, '百世汇通', '', 0, '', '', '', ''),
            (328, 0, '国际快递', '', 0, '', '', '', ''),
            (329, 0, 'Equick China', '', 0, '', '', '', ''),
            (330, 0, '北京网易速达', '', 0, '', '', '', ''),
            (331, 0, 'BOXC', '', 0, '', '', '', ''),
            (332, 0, 'BOXC快遞', '', 0, '', '', '', ''),
            (333, 0, 'Buylogic', '', 0, '', '', '', ''),
            (334, 0, '捷买送', '', 0, '', '', '', ''),
            (335, 0, 'Hong Kong Post', '', 0, '', '', '', ''),
            (336, 0, '香港郵政', '', 0, '', '', '', ''),
            (337, 0, 'EMPS Express', '', 0, '', '', '', ''),
            (338, 0, '快信快包', '', 0, '', '', '', ''),
            (339, 0, 'IDEX', '', 0, '', '', '', ''),
            (340, 0, '上海宏杉国际物流', '', 0, '', '', '', ''),
            (341, 0, 'SEKO Logistics', '', 0, '', '', '', ''),
            (342, 0, 'Hong Kong HKGSEKO', '', 0, '', '', '', ''),
            (343, 0, 'PFC Express', '', 0, '', '', '', ''),
            (344, 0, 'cPacket', '', 0, '', '', '', ''),
            (345, 0, 'YTO Express', '', 0, '', '', '', ''),
            (346, 0, 'TAQBIN Hong Kong', '', 0, '', '', '', ''),
            (347, 0, 'Yamat, 雅瑪多運輸- 宅急便', '', 0, '', '', '', ''),
            (348, 0, 'Detrack', '', 0, '', '', '', ''),
            (349, 0, 'Detrack Singapore', '', 0, '', '', '', ''),
            (350, 0, 'TGX', '', 0, '', '', '', ''),
            (351, 0, 'Top Gun Express, 精英速運', '', 0, '', '', '', ''),
            (352, 0, 'RAM', '', 0, '', '', '', ''),
            (353, 0, 'RAM Group', '', 0, '', '', '', ''),
            (354, 0, 'ZJS International', '', 0, '', '', '', ''),
            (355, 0, 'China CHN宅急送快運', '', 0, '', '', '', ''),
            (356, 0, 'Asendia UK', '', 0, '', '', '', ''),
            (357, 0, 'Asendia United Kingdom', '', 0, '', '', '', ''),
            (358, 0, 'Logistic Worldwide Express', '', 0, '', '', '', ''),
            (359, 0, 'Yun Express', '', 0, '', '', '', ''),
            (360, 0, '云途物流', '', 0, '', '', '', ''),
            (361, 0, 'Nationwide Express', '', 0, '', '', '', ''),
            (362, 0, 'nationwide2u', '', 0, '', '', '', ''),
            (363, 0, 'Cuckoo Express', '', 0, '', '', '', ''),
            (364, 0, '布谷鸟', '', 0, '', '', '', ''),
            (365, 0, 'RR Donnelley', '', 0, '', '', '', ''),
            (366, 0, 'RRD', '', 0, '', '', '', ''),
            (367, 0, 'Maxcellents Pte Ltd', '', 0, '', '', '', ''),
            (368, 0, 'Maxcellent', '', 0, '', '', '', ''),
            (369, 0, 'One World Express', '', 0, '', '', '', ''),
            (370, 0, 'u6613u65f6u9039u7269u6d41', '', 0, '', '', '', ''),
            (371, 0, 'Hua Han Logistics', '', 0, '', '', '', ''),
            (372, 0, 'China CHNu534eu7ff0u56fdu9645u7269u6d41', '', 0, '', '', '', ''),
            (373, 0, 'a j express', '', 0, '', '', '', ''),
            (374, 0, 'Hunter Express', '', 0, '', '', '', ''),
            (375, 0, 'Yakit', '', 0, '', '', '', ''),
            (376, 0, 'DHL Active Tracing', '', 0, '', '', '', ''),
            (377, 0, 'eParcel Korea', '', 0, '', '', '', ''),
            (378, 0, 'Yong Seoung', '', 0, '', '', '', ''),
            (379, 0, 'DEX-I', '', 0, '', '', '', ''),
            (380, 0, 'BRT Bartolini(Parcel ID)', '', 0, '', '', '', ''),
            (381, 0, 'BRT Corriere Espresso, DPD Italy', '', 0, '', '', '', ''),
            (382, 0, 'Homedirect Logistics', '', 0, '', '', '', ''),
            (383, 0, 'IMX Mail', '', 0, '', '', '', ''),
            (384, 0, 'CBL Logistics', '', 0, '', '', '', ''),
            (385, 0, 'Spain ESP', '', 0, '', '', '', ''),
            (386, 0, 'Easy Mail', '', 0, '', '', '', ''),
            (387, 0, 'DHL Hong Kong', '', 0, '', '', '', ''),
            (388, 0, 'DHL HK Domestic', '', 0, '', '', '', ''),
            (389, 0, 'RaidereX', '', 0, '', '', '', ''),
            (390, 0, 'Detrack', '', 0, '', '', '', ''),
            (391, 0, 'ITIS International', '', 0, '', '', '', ''),
            (392, 0, 'Panama PANITIS International', '', 0, '', '', '', ''),
            (393, 0, 'IMEX Global Solutions', '', 0, '', '', '', ''),
            (394, 0, 'Singapore Post', '', 0, '', '', '', ''),
            (395, 0, 'SingPost', '', 0, '', '', '', ''),
            (396, 0, 'RPX Online', '', 0, '', '', '', ''),
            (397, 0, 'Cathay Pacific', '', 0, '', '', '', ''),
            (398, 0, '17PostService', '', 0, '', '', '', ''),
            (399, 0, 'Nanjing Woyuan', '', 0, '', '', '', ''),
            (400, 0, 'Roadbull Logistics', '', 0, '', '', '', ''),
            (401, 0, 'Jersey Post', '', 0, '', '', '', ''),
            (402, 0, 'Directlog', '', 0, '', '', '', ''),
            (403, 0, 'Direct Express', '', 0, '', '', '', ''),
            (404, 0, 'Ekart', '', 0, '', '', '', ''),
            (405, 0, 'Ekart Logistics', '', 0, '', '', '', ''),
            (406, 0, 'Zyllem', '', 0, '', '', '', ''),
            (407, 0, 'RocketUncle', '', 0, '', '', '', ''),
            (408, 0, 'Singapore Speedpost', '', 0, '', '', '', ''),
            (409, 0, 'Singapore EMS', '', 0, '', '', '', ''),
            (410, 0, 'Yunda Express', '', 0, '', '', '', ''),
            (411, 0, '韵达快递', '', 0, '', '', '', ''),
            (412, 0, '360 Lion Express', '', 0, '', '', '', ''),
            (413, 0, 'GoFly', '', 0, '', '', '', ''),
            (414, 0, 'GoFlyi', '', 0, '', '', '', ''),
            (415, 0, 'DPE Express', '', 0, '', '', '', ''),
            (416, 0, 'Delivery Perfect Express Co.', '', 0, '', '', '', ''),
            (417, 0, 'SimplyPost', '', 0, '', '', '', ''),
            (418, 0, 'TAQBIN Singapore', '', 0, '', '', '', ''),
            (419, 0, 'Yamato Singapore', '', 0, '', '', '', ''),
            (420, 0, 'XQ Express', '', 0, '', '', '', ''),
            (421, 0, 'u661fu4e7eu7269u6d41', '', 0, '', '', '', ''),
            (422, 0, 'XL Express', '', 0, '', '', '', ''),
            (423, 0, 'Australia AUS', '', 0, '', '', '', ''),
            (424, 0, 'Ninja Van', '', 0, '', '', '', ''),
            (425, 0, 'VicTas Freight Express', '', 0, '', '', '', ''),
            (426, 0, 'VTFE', '', 0, '', '', '', ''),
            (427, 0, 'Zalora 7-Eleven', '', 0, '', '', '', ''),
            (428, 0, '7-11', '', 0, '', '', '', ''),
            (429, 0, 'Jet-Ship Worldwide', '', 0, '', '', '', ''),
            (430, 0, 'Nhans Solutions', '', 0, '', '', '', ''),
            (431, 0, 'Nhans Courier', '', 0, '', '', '', ''),
            (432, 0, 'KGM Hub', '', 0, '', '', '', ''),
            (433, 0, 'KGM', '', 0, '', '', '', ''),
            (434, 0, 'Qxpress', '', 0, '', '', '', ''),
            (435, 0, 'Qxpress Qoo10', '', 0, '', '', '', ''),
            (436, 0, 'RZY Express', '', 0, '', '', '', ''),
            (437, 0, 'RZYExpress', '', 0, '', '', '', ''),
            (438, 0, 'Parcel Post Singapore', '', 0, '', '', '', ''),
            (439, 0, 'ParcelPost', '', 0, '', '', '', ''),
            (440, 0, 'Parcel Express', '', 0, '', '', '', ''),
            (441, 0, 'Parcel Express Pte Ltd', '', 0, '', '', '', ''),
            (442, 0, 'Korea Post', '', 0, '', '', '', ''),
            (443, 0, 'CJ GLS', '', 0, '', '', '', ''),
            (444, 0, 'CJ Korea Express', '', 0, '', '', '', ''),
            (445, 0, 'Ecargo', '', 0, '', '', '', ''),
            (446, 0, 'SRE Korea', '', 0, '', '', '', ''),
            (447, 0, 'Rocket Parcel International', '', 0, '', '', '', ''),
            (448, 0, 'India Post Domestic', '', 0, '', '', '', ''),
            (449, 0, 'भारतीय डाक', '', 0, '', '', '', ''),
            (450, 0, 'India Post International', '', 0, '', '', '', ''),
            (451, 0, 'भारतीय डाक, Speed Post & eMO, EMS, IPS Web', '', 0, '', '', '', ''),
            (452, 0, 'Delhivery', '', 0, '', '', '', ''),
            (453, 0, 'Gharpay', '', 0, '', '', '', ''),
            (454, 0, 'Bluedart', '', 0, '', '', '', ''),
            (455, 0, 'Blue Dart Express', '', 0, '', '', '', ''),
            (456, 0, 'NuvoEx', '', 0, '', '', '', ''),
            (457, 0, 'Nuvo Ex', '', 0, '', '', '', ''),
            (458, 0, 'DTDC India', '', 0, '', '', '', ''),
            (459, 0, 'DTDC Courier & Cargo', '', 0, '', '', '', ''),
            (460, 0, 'Delcart', '', 0, '', '', '', ''),
            (461, 0, 'India IND', '', 0, '', '', '', ''),
            (462, 0, 'Professional Couriers', '', 0, '', '', '', ''),
            (463, 0, 'TPC India', '', 0, '', '', '', ''),
            (464, 0, 'Parcelled', '', 0, '', '', '', ''),
            (465, 0, 'Safexpress', '', 0, '', '', '', ''),
            (466, 0, 'Red Express', '', 0, '', '', '', ''),
            (467, 0, 'Red Express Waybill', '', 0, '', '', '', ''),
            (468, 0, 'First Flight Couriers', '', 0, '', '', '', ''),
            (469, 0, 'FirstFlight India', '', 0, '', '', '', ''),
            (470, 0, 'Gati-KWE', '', 0, '', '', '', ''),
            (471, 0, 'Gati-Kintetsu Express', '', 0, '', '', '', ''),
            (472, 0, 'GoJavas', '', 0, '', '', '', ''),
            (473, 0, 'Javas', '', 0, '', '', '', ''),
            (474, 0, 'Ecom Express', '', 0, '', '', '', ''),
            (475, 0, 'EcomExpress', '', 0, '', '', '', ''),
            (476, 0, 'XpressBees', '', 0, '', '', '', ''),
            (477, 0, 'XpressBees logistics', '', 0, '', '', '', ''),
            (478, 0, 'Japan Post', '', 0, '', '', '', ''),
            (479, 0, '日本郵便', '', 0, '', '', '', ''),
            (480, 0, 'Yamato Japan', '', 0, '', '', '', ''),
            (481, 0, 'ヤマト運輸, TAQBIN', '', 0, '', '', '', ''),
            (482, 0, 'Sagawa', '', 0, '', '', '', ''),
            (483, 0, '佐川急便', '', 0, '', '', '', ''),
            (484, 0, 'Taiwan Post', '', 0, '', '', '', ''),
            (485, 0, 'Chunghwa Post, 台灣中華郵政', '', 0, '', '', '', ''),
            (486, 0, 'JP BH Pošta', '', 0, '', '', '', ''),
            (487, 0, 'Bosnia & Herzegovina BIHBosnia and Herzegovina Post', '', 0, '', '', '', ''),
            (488, 0, 'Spreadel', '', 0, '', '', '', ''),
            (489, 0, 'Jabong delivery', '', 0, '', '', '', ''),
            (490, 0, 'Malaysia Post EMS / Pos Laju', '', 0, '', '', '', ''),
            (491, 0, 'Pos Ekspres, Pos Malaysia Express', '', 0, '', '', '', ''),
            (492, 0, 'Malaysia Post - Registered', '', 0, '', '', '', ''),
            (493, 0, 'PosDaftar', '', 0, '', '', '', ''),
            (494, 0, 'TAQBIN Malaysia', '', 0, '', '', '', ''),
            (495, 0, 'TAQBIN Malaysia', '', 0, '', '', '', ''),
            (496, 0, 'ABX Express', '', 0, '', '', '', ''),
            (497, 0, 'GDEX', '', 0, '', '', '', ''),
            (498, 0, 'GD Express', '', 0, '', '', '', ''),
            (499, 0, 'SkyNet Malaysia', '', 0, '', '', '', ''),
            (500, 0, 'City-Link Express', '', 0, '', '', '', ''),
            (501, 0, 'Citylink Malaysia', '', 0, '', '', '', ''),
            (502, 0, 'Mypostonline', '', 0, '', '', '', ''),
            (503, 0, 'MYBOXPOST', '', 0, '', '', '', ''),
            (504, 0, 'Airpak Express', '', 0, '', '', '', ''),
            (505, 0, 'Ninja Van Malaysia', '', 0, '', '', '', ''),
            (506, 0, 'Malaysia MYSNinjaVan MY', '', 0, '', '', '', ''),
            (507, 0, 'Matdespatch', '', 0, '', '', '', ''),
            (508, 0, 'Malaysia MYS', '', 0, '', '', '', ''),
            (509, 0, 'Thailand Thai Post', '', 0, '', '', '', ''),
            (510, 0, 'Thailand THAไปรษณีย์ไทย', '', 0, '', '', '', ''),
            (511, 0, 'Dynamic Logistics', '', 0, '', '', '', ''),
            (512, 0, 'Thailand THADynamic Logistics Thailand', '', 0, '', '', '', ''),
            (513, 0, '2GO', '', 0, '', '', '', ''),
            (514, 0, 'Negros Navigation', '', 0, '', '', '', ''),
            (515, 0, 'Courex', '', 0, '', '', '', ''),
            (516, 0, 'Singapore SGP', '', 0, '', '', '', ''),
            (517, 0, 'Xend Express', '', 0, '', '', '', ''),
            (518, 0, 'Xend Business Solutions', '', 0, '', '', '', ''),
            (519, 0, 'LBC Express', '', 0, '', '', '', ''),
            (520, 0, 'AIR21', '', 0, '', '', '', ''),
            (521, 0, 'AIR 21 PH', '', 0, '', '', '', ''),
            (522, 0, 'Jam Express', '', 0, '', '', '', ''),
            (523, 0, 'JAM Global Express', '', 0, '', '', '', ''),
            (524, 0, 'Airspeed International Corporation', '', 0, '', '', '', ''),
            (525, 0, 'Airspeed Philippines', '', 0, '', '', '', ''),
            (526, 0, 'RAF Philippines', '', 0, '', '', '', ''),
            (527, 0, 'RAF Int''l. Forwarding', '', 0, '', '', '', ''),
            (528, 0, 'Pos Indonesia Domestic', '', 0, '', '', '', ''),
            (529, 0, 'Indonesian Post Domestic', '', 0, '', '', '', ''),
            (530, 0, 'Pos Indonesia Int''l', '', 0, '', '', '', ''),
            (531, 0, 'Indonesian Post International EMS', '', 0, '', '', '', ''),
            (532, 0, 'Jayon Express (JEX)', '', 0, '', '', '', ''),
            (533, 0, 'JNE', '', 0, '', '', '', ''),
            (534, 0, 'Express Across Nation, Tiki Jalur Nugraha Ekakurir', '', 0, '', '', '', ''),
            (535, 0, 'Pandu Logistics', '', 0, '', '', '', ''),
            (536, 0, 'RPX Indonesia', '', 0, '', '', '', ''),
            (537, 0, 'Repex Perdana International', '', 0, '', '', '', ''),
            (538, 0, 'Tiki', '', 0, '', '', '', ''),
            (539, 0, 'Citra Van Titipan Kilat', '', 0, '', '', '', ''),
            (540, 0, 'Lion Parcel', '', 0, '', '', '', ''),
            (541, 0, 'Ninja Van Indonesia', '', 0, '', '', '', ''),
            (542, 0, 'Wahana', '', 0, '', '', '', ''),
            (543, 0, 'Wahana Indonesia', '', 0, '', '', '', ''),
            (544, 0, 'First Logistics', '', 0, '', '', '', ''),
            (545, 0, 'PT Synergy First Logistics', '', 0, '', '', '', ''),
            (546, 0, 'Vietnam Post', '', 0, '', '', '', ''),
            (547, 0, 'VNPost', '', 0, '', '', '', ''),
            (548, 0, 'Giao hàng nhanh', '', 0, '', '', '', ''),
            (549, 0, 'Giaohangnhanh.vn, GHN', '', 0, '', '', '', ''),
            (550, 0, 'Vietnam Post EMS', '', 0, '', '', '', ''),
            (551, 0, 'VNPost EMS', '', 0, '', '', '', ''),
            (552, 0, 'Lao Post', '', 0, '', '', '', ''),
            (553, 0, 'Lao People''s Democratic Republic LAOLaos Postal Service', '', 0, '', '', '', ''),
            (554, 0, 'ViettelPost', '', 0, '', '', '', ''),
            (555, 0, 'Bưu chính Viettel', '', 0, '', '', '', ''),
            (556, 0, 'Kerry TTC Express', '', 0, '', '', '', ''),
            (557, 0, 'KTTC', '', 0, '', '', '', ''),
            (558, 0, 'Cambodia Post', '', 0, '', '', '', ''),
            (559, 0, 'Australia Post', '', 0, '', '', '', ''),
            (560, 0, 'AusPost', '', 0, '', '', '', ''),
            (561, 0, 'Dotzot', '', 0, '', '', '', ''),
            (562, 0, 'Scudex Express', '', 0, '', '', '', ''),
            (563, 0, 'alphaFAST', '', 0, '', '', '', ''),
            (564, 0, 'Alpha', '', 0, '', '', '', ''),
            (565, 0, 'Toll IPEC', '', 0, '', '', '', ''),
            (566, 0, 'Toll Express', '', 0, '', '', '', ''),
            (567, 0, 'Toll Priority', '', 0, '', '', '', ''),
            (568, 0, 'Toll Group, Toll Priority', '', 0, '', '', '', ''),
            (569, 0, 'TNT Australia', '', 0, '', '', '', ''),
            (570, 0, 'TNT AU', '', 0, '', '', '', ''),
            (571, 0, 'ADSOne', '', 0, '', '', '', ''),
            (572, 0, 'Fastway Australia', '', 0, '', '', '', ''),
            (573, 0, 'Fastway Couriers', '', 0, '', '', '', ''),
            (574, 0, 'StarTrack', '', 0, '', '', '', ''),
            (575, 0, 'DTDC Australia', '', 0, '', '', '', ''),
            (576, 0, 'Sendle', '', 0, '', '', '', ''),
            (577, 0, 'Star Track Express', '', 0, '', '', '', ''),
            (578, 0, 'AaE Australian air Express', '', 0, '', '', '', ''),
            (579, 0, 'Couriers Please', '', 0, '', '', '', ''),
            (580, 0, 'CouriersPlease', '', 0, '', '', '', ''),
            (581, 0, 'New Zealand Post', '', 0, '', '', '', ''),
            (582, 0, 'Direct Freight Express', '', 0, '', '', '', ''),
            (583, 0, 'CourierPost', '', 0, '', '', '', ''),
            (584, 0, 'Express Couriers', '', 0, '', '', '', ''),
            (585, 0, 'Fastway New Zealand', '', 0, '', '', '', ''),
            (586, 0, 'UBI Logistics Australia', '', 0, '', '', '', ''),
            (587, 0, 'Bonds Couriers', '', 0, '', '', '', ''),
            (588, 0, 'Correos de Mexico', '', 0, '', '', '', ''),
            (589, 0, 'Mexico Post', '', 0, '', '', '', ''),
            (590, 0, 'Estafeta', '', 0, '', '', '', ''),
            (591, 0, 'Estafeta Mexicana', '', 0, '', '', '', ''),
            (592, 0, 'Mexico Senda Express', '', 0, '', '', '', ''),
            (593, 0, 'Mexico Senda Express', '', 0, '', '', '', ''),
            (594, 0, 'Mexico Redpack', '', 0, '', '', '', ''),
            (595, 0, 'TNT Mexico', '', 0, '', '', '', ''),
            (596, 0, 'Mexico AeroFlash', '', 0, '', '', '', ''),
            (597, 0, 'AeroFlash', '', 0, '', '', '', ''),
            (598, 0, 'Brazil Correios', '', 0, '', '', '', ''),
            (599, 0, 'Brazilian Post', '', 0, '', '', '', ''),
            (600, 0, 'Correos Chile', '', 0, '', '', '', ''),
            (601, 0, 'Chile Post', '', 0, '', '', '', ''),
            (602, 0, 'Correo Argentino', '', 0, '', '', '', ''),
            (603, 0, 'AArgentina Post', '', 0, '', '', '', ''),
            (604, 0, 'OCA Argentina', '', 0, '', '', '', ''),
            (605, 0, 'OCA e-Pak', '', 0, '', '', '', ''),
            (606, 0, 'Emirates Post', '', 0, '', '', '', ''),
            (607, 0, 'UAE Post', '', 0, '', '', '', ''),
            (608, 0, '4-72 Entregando', '', 0, '', '', '', ''),
            (609, 0, 'Colombia Postal Service', '', 0, '', '', '', ''),
            (610, 0, 'The Courier Guy', '', 0, '', '', '', ''),
            (611, 0, 'TheCourierGuy', '', 0, '', '', '', ''),
            (612, 0, 'South African Post Office', '', 0, '', '', '', ''),
            (613, 0, 'South African Post Office', '', 0, '', '', '', ''),
            (614, 0, 'Dawn Wing', '', 0, '', '', '', ''),
            (615, 0, 'DPD Laser Express Logistics', '', 0, '', '', '', ''),
            (616, 0, 'Fastway South Africa', '', 0, '', '', '', ''),
            (617, 0, 'Fastway Couriers', '', 0, '', '', '', ''),
            (618, 0, 'Specialised Freight', '', 0, '', '', '', ''),
            (619, 0, 'SFS', '', 0, '', '', '', ''),
            (620, 0, 'DPE South Africa', '', 0, '', '', '', ''),
            (621, 0, 'DPE Worldwide Express', '', 0, '', '', '', ''),
            (622, 0, 'SMSA Express', '', 0, '', '', '', ''),
            (623, 0, 'Saudi Arabia SAU', '', 0, '', '', '', ''),
            (624, 0, 'Courier IT', '', 0, '', '', '', ''),
            (625, 0, 'Courierit', '', 0, '', '', '', ''),
            (626, 0, 'Saudi Post', '', 0, '', '', '', ''),
            (627, 0, 'AXL Express & Logistics', '', 0, '', '', '', ''),
            (628, 0, 'AXL', '', 0, '', '', '', ''),
            (629, 0, 'NiPost', '', 0, '', '', '', ''),
            (630, 0, 'Nigerian Postal Service', '', 0, '', '', '', ''),
            (631, 0, 'Courier Plus', '', 0, '', '', '', ''),
            (632, 0, 'Courier Plus', '', 0, '', '', '', ''),
            (633, 0, 'Speedex Courier', '', 0, '', '', '', ''),
            (634, 0, 'Post Serbia', '', 0, '', '', '', ''),
            (635, 0, 'Pou0161ta Srbije', '', 0, '', '', '', ''),
            (636, 0, 'Asendia HK (LATAM)', '', 0, '', '', '', ''),
            (637, 0, 'SkyPostal (Postrac)', '', 0, '', '', '', ''),
            (638, 0, 'Kangaroo Worldwide Express', '', 0, '', '', '', ''),
            (639, 0, 'Fastrak Services', '', 0, '', '', '', ''),
            (640, 0, 'Fastrak Advanced Delivery Systems', '', 0, '', '', '', ''),
            (641, 0, 'Jocom', '', 0, '', '', '', ''),
            (642, 0, 'B2C Europe', '', 0, '', '', '', ''),
            (643, 0, 'Cosmetics Now', '', 0, '', '', '', '')";

    $sql[] = "REPLACE INTO `"._DB_PREFIX_."hl_carrier_text` (`id_carrier`, `text`, `state`) VALUES
        ('1','','2'),
        ('1','acheminement','3'),
        ('1','est livré','1'),
        ('1','gardien','1'),
        ('1','voisin','1'),
        ('2','','2'),
        ('2','acheminement','3'),
        ('2','livraison effectuée','1'),
        ('3','','2'),
        ('3','Réception','3'),
        ('3','a été livré','1'),
        ('5','','2'),
        ('5','Delivered','1'),
        ('5','Picked up','3'),
        ('6','','2'),
        ('6','Livré','1'),
        ('6','traitement','3'),
        ('8','','2'),
        ('8','Delivered','1'),
        ('8','In transit','3'),
        ('9','','2'),
        ('9','Lecture','3'),
        ('9','livré','1'),
        ('10','toto','1'),
        ('11','','2'),
        ('11','delivered','1'),
        ('11','processed','3'),
        ('12','Acceptance','3'),
        ('12','delivered','1'),
        ('13','delivered','1'),
        ('13','processed','3')";

    $sql[]  = 'ALTER TABLE `'._DB_PREFIX_.'hl_carrier` auto_increment = 1000';
    foreach ($sql as $s) {
        if (!Db::getInstance()->execute($s)) {
            return false;
        }
    }
}
