/*!40101 SET NAMES utf8 */;

/*!40101 SET SQL_MODE=''*/;

/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
/*Table structure for table `ps_amazon_states` */

DROP TABLE IF EXISTS `_DB_PREFIX_amazon_states`;

CREATE TABLE `_DB_PREFIX_amazon_states` (
  `country_iso` varchar(3) NOT NULL,
  `zipcode_start` varchar(8) NOT NULL,
  `state_iso` varchar(8) NOT NULL,
  `state_name` varchar(255) DEFAULT NULL,
  `note` varchar(255) DEFAULT NULL,
  UNIQUE KEY `country_iso` (`country_iso`,`zipcode_start`)
) ENGINE=InnoDB;

/*Data for the table `ps_amazon_states` */

insert  into `_DB_PREFIX_amazon_states`(`country_iso`,`zipcode_start`,`state_iso`,`state_name`,`note`) values 
('ES','01','ES-VI','Álava',NULL),
('ES','02','ES-AB','Albacete',NULL),
('ES','03','ES-A','Alacant',NULL),
('ES','04','ES-AL','Almería',NULL),
('ES','05','ES-AV','Ávila',NULL),
('ES','06','ES-BA','Badajoz',NULL),
('ES','07','ES-PM','Balears',NULL),
('ES','08','ES-B','Barcelona',NULL),
('ES','09','ES-BU','Burgos',NULL),
('ES','10','ES-CC','Cáceres',NULL),
('ES','11','ES-CA','Cádiz',NULL),
('ES','12','ES-CS','Castelló',NULL),
('ES','13','ES-CR','Ciudad Real',NULL),
('ES','14','ES-CO','Córdoba',NULL),
('ES','15','ES-C','A Coruña',NULL),
('ES','16','ES-CU','Cuenca',NULL),
('ES','17','ES-GI','Girona',NULL),
('ES','18','ES-GR','Granada',NULL),
('ES','19','ES-GU','Guadalajara',NULL),
('ES','20','ES-SS','Gipuzkoa',NULL),
('ES','21','ES-H','Huelva',NULL),
('ES','22','ES-HU','Huesca',NULL),
('ES','23','ES-J','Jaén',NULL),
('ES','24','ES-LE','León',NULL),
('ES','25','ES-L','Lleida',NULL),
('ES','26','ES-LO','La Rioja',NULL),
('ES','27','ES-LU','Lugo',NULL),
('ES','28','ES-M','Madrid',NULL),
('ES','29','ES-MA','Málaga',NULL),
('ES','30','ES-MU','Murcia',NULL),
('ES','31','ES-NA','Nafarroa',NULL),
('ES','32','ES-OR','Ourense',NULL),
('ES','33','ES-O','Asturias',NULL),
('ES','34','ES-P','Palencia',NULL),
('ES','35','ES-GC','Las Palmas',NULL),
('ES','36','ES-PO','Pontevedra',NULL),
('ES','37','ES-SA','Salamanca',NULL),
('ES','38','ES-TF','Santa Cruz de Tenerife',NULL),
('ES','39','ES-S','Cantabria',NULL),
('ES','40','ES-SG','Segovia',NULL),
('ES','41','ES-SE','Sevilla',NULL),
('ES','42','ES-SO','Soria',NULL),
('ES','43','ES-T','Tarragona',NULL),
('ES','44','ES-TE','Teruel',NULL),
('ES','45','ES-TO','Toledo',NULL),
('ES','46','ES-V','València',NULL),
('ES','47','ES-VA','Valladolid',NULL),
('ES','48','ES-BI','Bizkaia',NULL),
('ES','49','ES-ZA','Zamora',NULL),
('ES','50','ES-Z','Zaragoza',NULL),
('ES','51','ES-CE','Ceuta',NULL),
('ES','52','ES-ML','Melilla','Source: ME, PS: ML'),
('IT','00','RM','Roma',NULL),
('IT','00000','XXXX','CI,OG,OT,VS','Not existed yet: Carbonia-Iglesias,Ogliastra,Olbia-Tempio,Medio Campidano'),
('IT','01','VT','Viterbo',NULL),
('IT','02','RI','Rieti',NULL),
('IT','03','FR','Frosinone',NULL),
('IT','04','LT','Latina',NULL),
('IT','05','TR','Terni',NULL),
('IT','06','PG','Perugia',NULL),
('IT','07','SS','Sassari',NULL),
('IT','08','NU','Nuoro','Also contains OR, overlap SS'),
('IT','09','CA','Cagliari','Also contains OR, SU'),
('IT','10','TO','Torino',NULL),
('IT','11','AO','Aosta',NULL),
('IT','12','CN','Cuneo',NULL),
('IT','130','VC','Vercelli',NULL),
('IT','131','VC','Vercelli',NULL),
('IT','138','BI','Biella',NULL),
('IT','139','BI','Biella',NULL),
('IT','14','AT','Asti',NULL),
('IT','15','AL','Alessandria',NULL),
('IT','16','GE','Genova',NULL),
('IT','17','SV','Savona',NULL),
('IT','18','IM','Imperia',NULL),
('IT','19','SP','La Spezia',NULL),
('IT','200','MI','Milano',NULL),
('IT','201','MI','Milano',NULL),
('IT','208','MB','Monza e della Brianza',NULL),
('IT','209','MB','Monza e della Brianza',NULL),
('IT','21','VA','Varese',NULL),
('IT','22','CO','Como',NULL),
('IT','230','SO','Sondrio',NULL),
('IT','231','SO','Sondrio',NULL),
('IT','238','LC','Lecco',NULL),
('IT','24','BG','Bergamo',NULL),
('IT','25','BS','Brescia',NULL),
('IT','260','CR','Cremona',NULL),
('IT','261','CR','Cremona',NULL),
('IT','268','LO','Lodi',NULL),
('IT','269','LO','Lodi',NULL),
('IT','27','PV','Pavia',NULL),
('IT','280','NO','Novara',NULL),
('IT','281','NO','Novara',NULL),
('IT','288','VB','Verbano-Cusio-Ossola',NULL),
('IT','29','PC','Piacenza',NULL),
('IT','30','VE','Venezia',NULL),
('IT','31','TV','Treviso',NULL),
('IT','32','BL','Belluno',NULL),
('IT','3301','UD','Udine',NULL),
('IT','3302','UD','Udine',NULL),
('IT','3303','UD','Udine',NULL),
('IT','3304','UD','Udine',NULL),
('IT','3305','UD','Udine',NULL),
('IT','3306','UD','Udine',NULL),
('IT','3307','PN','Pordenone',NULL),
('IT','3308','PN','Pordenone',NULL),
('IT','3309','PN','Pordenone',NULL),
('IT','331','UD','Udine',NULL),
('IT','3317','PN','Pordenone',NULL),
('IT','3401','TS','Trieste',NULL),
('IT','3407','GO','Gorizia',NULL),
('IT','3412','TS','Trieste',NULL),
('IT','3413','TS','Trieste',NULL),
('IT','3414','TS','Trieste',NULL),
('IT','3417','GO','Gorizia',NULL),
('IT','35','PD','Padova',NULL),
('IT','36','VI','Vicenza',NULL),
('IT','37','VR','Verona',NULL),
('IT','38','TN','Trento',NULL),
('IT','39','BZ','Bolzano',NULL),
('IT','40','BO','Bologna',NULL),
('IT','41','MO','Modena',NULL),
('IT','42','RE','Reggio Emilia',NULL),
('IT','43','PR','Parma',NULL),
('IT','44','FE','Ferrara',NULL),
('IT','45','RO','Rovigo',NULL),
('IT','46','MN','MN',NULL),
('IT','470','FC','Forlì-Cesena',NULL),
('IT','471','FC','Forlì-Cesena',NULL),
('IT','478','RN','Rimini',NULL),
('IT','479','RN','Rimini',NULL),
('IT','48','RA','Ravenna',NULL),
('IT','50','FI','Firenze',NULL),
('IT','51','PT','Pistoia',NULL),
('IT','52','AR','Arezzo',NULL),
('IT','53','SI','Siena',NULL),
('IT','54','MS','Massa',NULL),
('IT','55','LU','Lucca',NULL),
('IT','56','PI','Pisa',NULL),
('IT','57','LI','Livorno',NULL),
('IT','58','GR','Grosseto',NULL),
('IT','59','PO','Prato',NULL),
('IT','60','AN','Ancona',NULL),
('IT','61','PU','Pesaro-Urbino',NULL),
('IT','62','MC','Macerata',NULL),
('IT','630','AP','Ascoli Piceno',NULL),
('IT','631','AP','Ascoli Piceno',NULL),
('IT','638','FM','Fermo',NULL),
('IT','639','FM','Fermo',NULL),
('IT','64','TE','Teramo',NULL),
('IT','65','PE','Pescara',NULL),
('IT','66','CH','Chieti',NULL),
('IT','67','AQ','L\'Aquila',NULL),
('IT','70','BA','Bari',NULL),
('IT','71','FG','Foggia',NULL),
('IT','72','BR','Brindisi',NULL),
('IT','73','LE','Lecce',NULL),
('IT','74','TA','Taranto',NULL),
('IT','75','MT','Matera',NULL),
('IT','76','BT','Barletta-Andria-Trani',NULL),
('IT','80','NA','Napoli',NULL),
('IT','81','CE','Caserta',NULL),
('IT','82','BN','Benevento',NULL),
('IT','83','AV','Avellino',NULL),
('IT','84','SA','Salerno',NULL),
('IT','85','PZ','Potenza',NULL),
('IT','8601','CB','Campobasso',NULL),
('IT','8602','CB','Campobasso',NULL),
('IT','8603','CB','Campobasso',NULL),
('IT','8604','CB','Campobasso',NULL),
('IT','8607','IS','Isernia',NULL),
('IT','8608','IS','Isernia',NULL),
('IT','8609','IS','Isernia',NULL),
('IT','8610','CB','Campobasso',NULL),
('IT','8617','IS','Isernia',NULL),
('IT','87','CS','Cosenza',NULL),
('IT','880','CZ','Catanzaro',NULL),
('IT','881','CZ','Catanzaro',NULL),
('IT','888','KR','Crotone',NULL),
('IT','889','KR','Crotone',NULL),
('IT','890','RC','Reggio Calabria',NULL),
('IT','891','RC','Reggio Calabria',NULL),
('IT','898','VV','Vibo Valentia',NULL),
('IT','899','VV','Vibo Valentia',NULL),
('IT','90','PA','Palermo',NULL),
('IT','91','TP','Trapani',NULL),
('IT','92','AG','Agrigento',NULL),
('IT','93','CL','Caltanissetta',NULL),
('IT','94','EN','Enna',NULL),
('IT','95','CT','Catania',NULL),
('IT','96','SR','Siracusa',NULL),
('IT','97','RG','Ragusa',NULL),
('IT','98','ME','Messina',NULL);

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
